Added documentation installation to existing install scripts.
git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@3383 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/install/install/get_paths b/install/install/get_paths
--- a/install/install/get_paths
+++ b/install/install/get_paths
@@ -1,90 +1,103 @@
 #!/bin/csh -f
 #
-#      $Id: get_paths,v 1.2 1993-02-22 18:45:22 clyne Exp $
+#      $Id: get_paths,v 1.3 1995-06-07 17:17:37 haley Exp $
 #
 #########################################################################
-#									#
-#			   Copyright (C)  1992				#
-#	     University Corporation for Atmospheric Research		#
-#			   All Rights Reserved				#
-#									#
+#                                                                       #
+#              Copyright (C)  1992                                      #
+#        University Corporation for Atmospheric Research                #
+#              All Rights Reserved                                      #
+#                                                                       #
 #########################################################################
 #
-#	File:		get_paths
+#   File:       get_paths
 #
-#	Author:		John Clyne
-#			National Center for Atmospheric Research
-#			PO 3000, Boulder, Colorado
+#   Author:     John Clyne
+#           National Center for Atmospheric Research
+#           PO 3000, Boulder, Colorado
 #
-#	Date:		Tue Sep 29 09:27:42 MDT 1992
+#   Date:       Tue Sep 29 09:27:42 MDT 1992
 #
-#	Description:	Get the installation paths for bin, include, lib
-#			and man directories. If get_paths exits with a
-#			0 exit status then the bin, include, lib, and man
-#			paths are written to stdout as a space-separated 
-#			single line in that order. If the user requests that
-#			a particular component of NCAR G not be installed the
-#			coresponding path for that component is set to 
-#			"/dev/null".
+#   Description:    Get the installation paths for bin, include, lib
+#           and man or the documentation directories. If get_paths exits
+#           with a 0 exit status then the paths paths are written to
+#           stdout as a space-separated single line in that order.
+#           If the user requests that a particular component of NCARG
+#           not be installed the corresponding path for that component
+#           is set to "/dev/null".
 #
-#			get_paths verifies that the given directories
-#			have appropriate permissions and that the file
-#			systems they are part of have enough space.
+#           get_paths verifies that the given directories
+#           have appropriate permissions and that the file
+#           systems they are part of have enough space.
 #
-#			get_paths also warns the user if he tries to select
-#			installation paths with different parents such that
-#			multiple NCARG_* variables would be required to
-#			use NCAR G.
-#			
+#           get_paths also warns the user if he tries to select
+#           installation paths with different parents such that
+#           multiple NCARG_* variables would be required to
+#           use NCAR G.
+#           
+#           When invoked with the -default option the user
+#           is not prompted for individual installation 
+#           directories. Instead the default installation paths
+#           are assumed. get_paths simply checks the permissions
+#           of the default directories and verifies that there
+#           is enough space.  When invoked with the -doc option, then
+#           documentation paths are looked up instead.
 #
-#			When invoked with the -default option the user
-#			is not prompted for individual installation 
-#			directories. Instead the default installation paths
-#			are assumed. get_paths simply checks the permissions
-#			of the default directories and verifies that there
-#			is enough space.
+#   Usage:      get_paths [ -default ] [ -doc ]
 #
-#	Usage:		get_paths [ -default ]
+#   Environment:    SYSTEM      : system type
+#           LOCALDIR    : path to install system
 #
-#	Environment:	SYSTEM		: system type
-#			LOCALDIR	: path to install system
-#
-#	Files:
+#   Files:
 #
 #
-#	Options:	-default	: force default installation paths
+#   Options:    -default    : force default installation paths
+#   Options:    -doc        : look up documentation paths
 
 onintr cleanup
 
 set do_default = 0	# do default installation?
+set do_doc = 0		# do documentation installation?
 set do_bin = 1		# do install executables?
 set do_inc = 1		# do install C includes?
 set do_lib = 1		# do install libraries?
 set do_man = 1		# do install man pages?
+set do_htmldoc = 1  # do install HTML documentation?
+set do_psdoc = 1    # do install PostScript documentation?
 
-if ($#argv > 1) then
-	echo "Usage: get_paths [-default]" > /dev/tty
+if ($#argv > 2) then
+	echo "Usage: get_paths [-doc] [-default]" > /dev/tty
 	exit 1
 endif
 
-if ($#argv == 1) then
-	if ("$argv[1]" != "-default") then
-		echo "Usage: get_paths [-default]" > /dev/tty
-		exit 1
-	endif
+while ($#argv > 0) 
+  switch ($1)
+    case "-default":
 	set do_default = 1
-endif
+    shift
+    breaksw
 
+    case "-doc":
+    set do_doc = 1
+    shift
+    breaksw
+
+    default:
+	echo "Usage: get_paths [-default] [-doc]" > /dev/tty
+	exit 1
+    breaksw
+  endsw
+end
 
 #
 #	get default paths for this directory. paths.$SYSTEM sets the
-#	bin_path, lib_path, inc_path, and man_path variables
+#	bin_path, lib_path, inc_path, man_path, psdoc_path and htmldoc_path
+#	variables.
 #
 source $LOCALDIR/config/paths.$SYSTEM
 
-
-if (! "$do_default") then
-
+if (! "$do_doc") then
+  if (! "$do_default") then
 	set bin_item = "Install executables"
 	set inc_item = "Install C include files"
 	set lib_item = "Install libraries"
@@ -211,9 +224,9 @@ if (! "$do_default") then
 		end
 	endif
 
-endif	# if (! do_default)
+  endif	# if (! do_default)
 
-foreach dir ("$bin_path" "$inc_path" "$lib_path" "$man_path")
+  foreach dir ("$bin_path" "$inc_path" "$lib_path" "$man_path")
 	if ("$dir" != "/dev/null") then
 		$LOCALDIR/permissions +d +w $dir
 		if ($status != 0) then
@@ -235,55 +248,193 @@ EOF
 			endif
 		endif
 	endif	# if  (/dev/null)
-end
+  end
 
 #
 #       get size requirements for each installed directory
 #
-set sizes = `$LOCALDIR/get_sizes`
-if ($status != 0) then
-        exit 1
-endif
+  set sizes = `$LOCALDIR/get_sizes`
+  if ($status != 0) then
+    exit 1
+  endif
 
-if ("$do_bin") then
+  if ("$do_bin") then
 	set bin_size = $sizes[1]
-else
+  else
 	set bin_size = 0
-endif
+  endif
 
-if ("$do_inc") then
+  if ("$do_inc") then
 	set inc_size = $sizes[2]
-else
+  else
 	set inc_size = 0
-endif
-if ("$do_lib") then
+  endif
+  if ("$do_lib") then
 	set lib_size = $sizes[3]
-else
+  else
 	set lib_size = 0
-endif
-if ("$do_man") then
+  endif
+  if ("$do_man") then
 	set man_size = $sizes[4]
-else
+  else
 	set man_size = 0
-endif
+  endif
 
-echo "" > /dev/tty
-echo "" > /dev/tty
-echo "	Calculating disk space... This may take a couple of minutes" >> /dev/tty
+  echo "" > /dev/tty
+  echo "" > /dev/tty
+  echo "	Calculating disk space... This may take a couple of minutes" >> /dev/tty
 
-$LOCALDIR/spaceok $bin_path $bin_size $inc_path $inc_size $lib_path $lib_size $man_path $man_size
+  $LOCALDIR/spaceok $bin_path $bin_size $inc_path $inc_size $lib_path $lib_size $man_path $man_size
 
-if ($status != 0) then
-
+  if ($status != 0) then
 	$LOCALDIR/pause
 	if ("$do_default") then
 		exit 1
 	endif
 	goto get_path_from_user
-endif
+  endif
+
+  echo "$bin_path $inc_path $lib_path $man_path"
+
+else
+  if (! "$do_default") then
+	set htmldoc_item = "Install HTML documentation"
+	set psdoc_item = "Install PostScript documentation"
+
+	#
+	# find out which software components the user wants to install
+	#
+	set select_vector = `$LOCALDIR/list_menu "$htmldoc_item" "$psdoc_item"`
+
+	if ($status != 0) then
+		exit 1
+	endif 
+
+	set do_htmldoc = $select_vector[1]
+	set do_psdoc = $select_vector[2]
+
+	#
+	# fake out the compare_paths script by setting unused installation
+	# directories to /dev/null
+	#
+	if (! "$do_htmldoc") set htmldoc_path = "/dev/null"
+	if (! "$do_psdoc") set psdoc_path = "/dev/null"
+	
+	clear > /dev/tty
+	echo "" > /dev/tty
+	echo "" > /dev/tty
+	echo "" > /dev/tty
+	echo "	The default installation directories for your system" > /dev/tty
+	echo "	are:" > /dev/tty
+	echo "" > /dev/tty
+
+	if ("$do_htmldoc") then
+		echo "	HTML documentation		: $htmldoc_path">/dev/tty
+	endif
+
+    if ("$do_psdoc") then
+        echo "	PostScript documentation	: $psdoc_path">/dev/tty
+	endif
+
+	echo "" > /dev/tty
+
+	echo "	It is recommended that you use the default" > /dev/tty
+	echo "	installation path(s). Do you wish to use the" > /dev/tty
+	echo "	default (y)?" > /dev/tty
+	echo "" > /dev/tty
+
+	echo -n "Enter Return(default), y(yes), n(no), or p(previous menu) > "> /dev/tty
+	set answer = $<
+
+	if ("$answer" == "p") goto cleanup
+
+	if ("$answer" == "n") then
+	get_doc_path_from_user:
+		set done = 0
+		set htmldoc_prompt = "HTML documentation installation directory"
+		set psdoc_prompt = "PostScript documentation installation directory"
+		while (! "$done") 
+			clear > /dev/tty
+
+			if ("$do_htmldoc") then
+			  set htmldoc_path = `$LOCALDIR/get_path "$htmldoc_prompt" $htmldoc_path`
+			  if ($status != 0) goto cleanup
+			endif	# if (do_htmldoc)
+				
+			if ("$do_psdoc") then
+			  set psdoc_path = `$LOCALDIR/get_path "$psdoc_prompt" $psdoc_path`
+			  if ($status != 0) goto cleanup
+			endif	# if ("do_psdoc")
+
+			set done = 1
+		end
+	endif
+
+  endif	# if (! do_default)
+
+  foreach dir ("$htmldoc_path" "$psdoc_path")
+	if ("$dir" != "/dev/null") then
+		$LOCALDIR/permissions +d +w $dir
+		if ($status != 0) then
+			mkdir $dir
+			if ($status != 0) then
+				cat > /dev/tty <<EOF
 
 
-echo "$bin_path $inc_path $lib_path $man_path"
+		The directory path $dir either does not exist 
+		and could not be created, or it exists but is not writable.  
+		Please create $dir and try again, or 
+		select another path.
+EOF
+				$LOCALDIR/pause
+				if ("$do_default") then
+					exit 1
+				endif
+				goto get_doc_path_from_user
+			endif
+		endif
+	endif	# if  (/dev/null)
+  end
+
+#
+#       get size requirements for each installed directory
+#
+  set sizes = `$LOCALDIR/get_sizes -d`
+  if ($status != 0) then
+        exit 1
+  endif
+
+  if ("$do_htmldoc") then
+	set htmldoc_size = $sizes[1]
+  else
+	set htmldoc_size = 0
+  endif
+
+  if ("$do_psdoc") then
+	set psdoc_size = $sizes[2]
+  else
+	set psdoc_size = 0
+  endif
+
+  echo "" > /dev/tty
+  echo "" > /dev/tty
+  echo "	Calculating disk space... This may take a couple of minutes" >> /dev/tty
+
+  $LOCALDIR/spaceok $htmldoc_path $htmldoc_size $psdoc_path $psdoc_size
+
+  if ($status != 0) then
+	$LOCALDIR/pause
+	if ("$do_default") then
+		exit 1
+	endif
+	goto get_doc_path_from_user
+  endif
+
+
+  echo  "$htmldoc_path $psdoc_path"
+
+endif	# if (! do_doc)
+
 exit 0
 
 cleanup:
diff --git a/install/install/get_sizes b/install/install/get_sizes
--- a/install/install/get_sizes
+++ b/install/install/get_sizes
@@ -1,59 +1,96 @@
 #!/bin/csh -f
 #########################################################################
-#									#
-#			   Copyright (C)  1992				#
-#	     University Corporation for Atmospheric Research		#
-#			   All Rights Reserved				#
-#									#
+#                                                                       #
+#              Copyright (C)  1992                                      #
+#        University Corporation for Atmospheric Research                #
+#              All Rights Reserved                                      #
+#                                                                       #
 #########################################################################
 #
-#	File:		get_sizes
+#   File:       get_sizes
 #
-#	Author:		John Clyne
-#			National Center for Atmospheric Research
-#			PO 3000, Boulder, Colorado
+#   Author:     John Clyne
+#           National Center for Atmospheric Research
+#           PO 3000, Boulder, Colorado
 #
-#	Date:		Mon Nov 9 16:07:53 MST 1992
+#   Date:       Mon Nov 9 16:07:53 MST 1992
 #
-#	Description:	Report the size requirements for the installation.
-#			If get_sizes exits with a zero exit status then
-#			the minimum size requirements for bin, include, 
-#			lib, and man directories are written to stdout
-#			as a space-separated, single line, in that order.
+#   Description:    Report the size requirements for the installation.
+#           If get_sizes exits with a zero exit status then
+#           the minimum size requirements for bin, include, 
+#           lib, and man directories are written to stdout
+#           as a space-separated, single line, in that order.
 #
-#			If the -t option is used only the total for
-#			bin, include, lib and man directories will be
-#			reported.
-#
-#
-#	Usage:		get_sizes [-t]
-#
-#	Environment:	SYSTEM		: system type
-#			LOCALDIR	: path to install system
-#
-#	Files:		$LOCALDIR/var/sizes.$system	space requirements
-#					for system $SYSTEM
+#           If the -t option is used only the total for
+#           bin, include, lib and man directories will be
+#           reported.  If the -d option is used, only sizes
+#           for documentation will be reported.
 #
 #
-#	Options:
+#	Usage:		get_sizes [-t] [-d]
+#
+#   Environment:    SYSTEM      : system type
+#           LOCALDIR    : path to install system
+#
+#   Files:      $LOCALDIR/var/sizes.$system space requirements
+#                   for system $SYSTEM
+#
+#
+#   Options:
 
 onintr cleanup
 
 set do_total = 0
+set do_doc = 0
 
-if ($#argv > 1) then
-	echo "Usage: get_sizes [-t]" > /dev/tty
+if ($#argv > 2) then
+	echo "Usage: get_sizes [-t] [-d]" > /dev/tty
 	exit 1
 endif
 
-if ($#argv == 1) then
-	if ("$argv[1]" != "-t") then
-		echo "Usage: get_sizes [-t]" > /dev/tty
+while ($#argv > 0) 
+  switch ($1)
+    case "-t":
+	set do_total = 1
+    shift
+    breaksw
+
+    case "-d":
+    set do_doc = 1
+    shift
+    breaksw
+
+    default:
+	echo "Usage: get_sizes [-t] [-d]" > /dev/tty
+	exit 1
+    breaksw
+  endsw
+end
+
+if ("$do_doc") then
+	set cmd = "grep html $LOCALDIR/var/sizes.$DOC"
+	set size_line = `$cmd`
+	if ($status != 0) then
+		echo "$0 : <$cmd> - failed" > /dev/tty
 		exit 1
 	endif
-	set do_total = 1
-endif
+	set htmldoc_size = $size_line[2]
 
+	set cmd = "grep ps $LOCALDIR/var/sizes.$DOC"
+	set size_line = `$cmd`
+	if ($status != 0) then
+		echo "$0 : <$cmd> - failed" > /dev/tty
+		exit 1
+	endif
+	set psdoc_size = $size_line[2]
+
+	if ("$do_total") then
+		@ total = $psdoc_size + $htmldoc_size
+		echo "$total"
+	else
+		echo " $htmldoc_size $psdoc_size"
+	endif
+else
 	set cmd = "grep bin $LOCALDIR/var/sizes.$SYSTEM"
 	set size_line = `$cmd`
 	if ($status != 0) then
@@ -88,10 +125,11 @@ endif
 
 	if ("$do_total") then
 		@ total = $bin_size + $inc_size + $lib_size + $man_size
-		echo $total
+		echo "$total"
 	else
 		echo "$bin_size $inc_size $lib_size $man_size"
 	endif
+endif
 
 exit 0
 
diff --git a/install/install/select_config b/install/install/select_config
--- a/install/install/select_config
+++ b/install/install/select_config
@@ -1,13 +1,13 @@
 #!/bin/csh -f
 #
-#      $Id: select_config,v 1.4 1995-04-08 16:24:43 haley Exp $
+#      $Id: select_config,v 1.5 1995-06-07 17:17:40 haley Exp $
 #
 #########################################################################
-#									#
-#			   Copyright (C)  1992				#
-#	     University Corporation for Atmospheric Research		#
-#			   All Rights Reserved				#
-#									#
+#                                                                       #
+#              Copyright (C)  1992                                      #
+#        University Corporation for Atmospheric Research                #
+#              All Rights Reserved                                      #
+#                                                                       #
 #########################################################################
 #
 #	File:		select_config
@@ -21,12 +21,12 @@
 #	Description:	Select an installation configuration. On success,
 #			exit status == 0, select_config writes the installation
 #			type (Basic-Installation or Custom-Installation), 
-#			the bin, include, lib, and man paths, in that order,
-#			to the standard output. If no selection was made
-#			select_config will not write anything to stdout.
-#			If an error occurs exit status will be 1.
+#			the bin, include, lib, and man paths (or the documentation
+#			paths) in that order, to the standard output. If no
+#			selection was made select_config will not write anything
+#			to stdout.  If an error occurs exit status will be 1.
 #
-#	Usage:		select_config
+#	Usage:		select_config [-d]
 #
 #	Environment:	SYSTEM		: system type
 #			LOCALDIR	: path to install system
@@ -34,13 +34,34 @@
 #	Files:
 #
 #
-#	Options:
+#   Options:    -doc        : look up documentation paths
+#
 
 onintr cleanup
 
+set do_doc = 0
+
+if ($#argv > 1) then
+	echo "Usage: select_config [-doc]" > /dev/tty
+	exit 1
+endif
+
+if ($#argv == 1) then
+  if ("$argv[1]" == "-doc") then
+    set do_doc = 1
+  else
+	echo "Usage: select_config [-doc]" > /dev/tty
+	exit 1
+  endif
+endif
+
 clear > /dev/tty
 
-set total_size = `$LOCALDIR/get_sizes -t`
+if ("$do_doc") then
+  set total_size = `$LOCALDIR/get_sizes -t -d`
+else
+  set total_size = `$LOCALDIR/get_sizes -t`
+endif
 if ($status != 0) then
 	exit 1
 endif
@@ -87,7 +108,11 @@ EOF
 			# call get_paths to determine if there is enough 
 			# disk space
 			#
-			set paths = `$LOCALDIR/get_paths -default`
+            if ("$do_doc") then
+			  set paths = `$LOCALDIR/get_paths -default -doc`
+            else
+			  set paths = `$LOCALDIR/get_paths -default`
+            endif
 			if ($status == 0) then
 				set done = 1
 				set type = "Basic-Installation"
@@ -101,7 +126,11 @@ EOF
 			#
 			# get the installation directory paths
 			#
-			set paths = `$LOCALDIR/get_paths`
+            if ("$do_doc") then
+  			  set paths = `$LOCALDIR/get_paths -doc`
+            else
+  			  set paths = `$LOCALDIR/get_paths`
+            endif
 			if ($status == 0) then
 				set done = 1
 				set type = "Custom-Installation"
@@ -111,10 +140,28 @@ EOF
 			breaksw
 
 		case "3":
-			source $LOCALDIR/config/paths.$SYSTEM
+		  	source $LOCALDIR/config/paths.$SYSTEM
 			clear > /dev/tty
-			cat <<EOF > /dev/tty
+            if ("$do_doc") then
+  			  cat <<EOF > /dev/tty
 
+	The Basic Documentation Installation installs all documentation
+	components of NCAR Graphics Version $VERSION:
+
+		HTML documents are installed to $htmldoc_path.
+		PostScript documents are installed to $psdoc_path. 
+
+	The Custom Installation allows you some freedom in choosing which 
+	components of the NCAR Graphics documentation are installed. For
+	example, if you only need to install the HTML documentation, you
+	should select the Custom Installation. In addition, the custom
+	installation allows you to choose the installation paths of the
+	PostScript and HTML documentation directories.  It is recommended
+	that you install the PostScript documentation to the directory
+	NCARG_ROOT/lib/ncarg/doc, just for the sake of consistency.
+EOF
+            else
+  			  cat <<EOF > /dev/tty
 
 	The Basic Installation installs all components of NCAR Graphics
 	Version $VERSION:
@@ -134,6 +181,8 @@ EOF
 	It is highly recommended that less experienced installers choose
 	the basic installation.
 EOF
+            endif
+       
 			$LOCALDIR/pause
 
 			breaksw
@@ -152,14 +201,22 @@ EOF
 end
 
 
+if ("$do_doc") then
+  set htmldoc_path = $paths[1]
+  set psdoc_path = $paths[2]
 
+  echo $type $htmldoc_path $psdoc_path
 
-set bin_path = $paths[1]
-set inc_path = $paths[2]
-set lib_path = $paths[3]
-set man_path = $paths[4]
+else
+  set bin_path = $paths[1]
+  set inc_path = $paths[2]
+  set lib_path = $paths[3]
+  set man_path = $paths[4]
 
-echo $type $bin_path $inc_path $lib_path $man_path
+  echo $type $bin_path $inc_path $lib_path $man_path
+
+endif
+
 
 exit 0
 
