Removed old doc stuff.
git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@3597 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/install/install/INSTALL b/install/install/INSTALL
--- a/install/install/INSTALL
+++ b/install/install/INSTALL
@@ -1,6 +1,6 @@
 #!/bin/csh -f
 #
-#      $Id: INSTALL,v 1.8 1995-08-22 21:17:36 haley Exp $
+#      $Id: INSTALL,v 1.9 1995-10-05 21:58:58 haley Exp $
 #
 #########################################################################
 #                                                                       #
@@ -38,11 +38,11 @@
 #
 set dir = `expr \( x"$0" : x'\(/\)$' \) \| \( x"$0" : x'\(.*\)/[^/]*$' \) \| .`
 if ($status != 0) then
-	echo "$0 : Can't find working directory, <expr> failed" > /dev/tty
-	exit 1
+    echo "$0 : Can't find working directory, <expr> failed" > /dev/tty
+    exit 1
 endif
 
-setenv LOCALDIR	"$dir"
+setenv LOCALDIR "$dir"
 
 setenv SYSTEM `$LOCALDIR/sys_type`
 if ($status != 0) then
@@ -52,7 +52,7 @@ endif
 setenv VERSION `cat $LOCALDIR/var/version.$SYSTEM`
 
 while (1) 
-	clear
+    clear
 cat <<EOF
 
 
@@ -63,100 +63,90 @@ cat <<EOF
 
 
 
-
-
-	1.  Ordering information
+        1.  Ordering information
         2.  Install software
-        3.  Install documentation
-        4.  Remove installed software
-        5.  Help
+        3.  Remove installed software
+        4.  Help
 
-	0.  Exit
+        0.  Exit
 
 EOF
 
-	echo -n "    Select: "
-	set answer =  $<
-	switch ("$answer")
-	case "1":
-		clear
-		cat <<EOF
+    echo -n "    Select: "
+    set answer =  $<
+    switch ("$answer")
+    case "1":
+        clear
+        cat <<EOF
 
 
 
-	To order NCAR Graphics or request further information please call
-	or write NCAR Graphics Information:
+    To order NCAR Graphics or request further information please call
+    or write NCAR Graphics Information:
 
-		University Corporation for Atmospheric Research
-		SCD/NCAR Graphics Orders
-		P.O. Box 3000
-		Boulder, CO 80307-3000 (USA)
+        University Corporation for Atmospheric Research
+        SCD/NCAR Graphics Orders
+        P.O. Box 3000
+        Boulder, CO 80307-3000 (USA)
 
-		Telephone:	(303) 497-1201
-		Telex:		989764
-		FAX:		(303) 497-1814
-		email:		scdinfo@ncar.ucar.edu
+        Telephone:  (303) 497-1201
+        Telex:      989764
+        FAX:        (303) 497-1814
+        email:      scdinfo@ncar.ucar.edu
 EOF
-		$LOCALDIR/pause
-		
-	
-		breaksw
+        $LOCALDIR/pause
+        
+    
+        breaksw
 
-	case "2":
-		$LOCALDIR/install_soft
-		if ($status != 0) then
-			$LOCALDIR/pause
-		endif
-		breaksw
+    case "2":
+        $LOCALDIR/install_soft
+        if ($status != 0) then
+            $LOCALDIR/pause
+        endif
+        breaksw
 
-	case "3":
-		$LOCALDIR/install_soft -doc
-		if ($status != 0) then
-			$LOCALDIR/pause
-		endif
-		breaksw
+    case "3":
+        $LOCALDIR/remove_soft
+        if ($status != 0) then
+            $LOCALDIR/pause
+        endif
+        breaksw
 
-	case "4":
-		$LOCALDIR/remove_soft
-		if ($status != 0) then
-			$LOCALDIR/pause
-		endif
-		breaksw
+    case "4":
 
-	case "5":
-
-		clear
-		cat <<EOF
+        clear
+        cat <<EOF
 
 
-	This is the main menu for the NCAR Graphics software installation
-	program. From this menu you may choose to: 
+    This is the main menu for the NCAR Graphics software installation
+    program. From this menu you may choose to: 
 
-		1. Get information on ordering NCAR Graphics.
+        1. Get information on ordering NCAR Graphics.
 
-		2. Install NCAR Graphics software.
+        2. Install NCAR Graphics software.
 
-		3. Remove previously installed versions of NCAR Graphics.
+        3. Remove previously installed versions of NCAR Graphics.
 
-		4. Print this help message.
+        4. Print this help message.
 
-		0. Exit the INSTALL program.
+        0. Exit the INSTALL program.
 EOF
-		$LOCALDIR/pause
-		breaksw
+        $LOCALDIR/pause
+        breaksw
 
-	case "99":
-		$PAGER bambi1.ani
-		breaksw
-	case "0":
-		exit 0
-		breaksw
+    case "99":
+        $PAGER bambi1.ani
+        breaksw
+    case "0":
+        exit 0
+        breaksw
 
-	case ""
-		breaksw
+    case ""
+        breaksw
 
-	default
-		echo "Invalid option <$answer>"
-		$LOCALDIR/pause
-	endsw
+    default
+        echo "Invalid option <$answer>"
+        $LOCALDIR/pause
+    endsw
 end
diff --git a/install/install/get_sizes b/install/install/get_sizes
--- a/install/install/get_sizes
+++ b/install/install/get_sizes
@@ -23,11 +23,9 @@
 #
 #           If the -t option is used only the total for
 #           bin, include, lib and man directories will be
-#           reported.  If the -d option is used, only sizes
-#           for documentation will be reported.
+#           reported.
 #
-#
-#	Usage:		get_sizes [-t] [-d]
+#   Usage:      get_sizes [-t]
 #
 #   Environment:    SYSTEM      : system type
 #           LOCALDIR    : path to install system
@@ -41,95 +39,58 @@
 onintr cleanup
 
 set do_total = 0
-set do_doc = 0
 
-if ($#argv > 2) then
-	echo "Usage: get_sizes [-t] [-d]" > /dev/tty
-	exit 1
+if ($#argv > 1) then
+    echo "Usage: get_sizes [-t]" > /dev/tty
+    exit 1
 endif
 
-while ($#argv > 0) 
-  switch ($1)
-    case "-t":
-	set do_total = 1
-    shift
-    breaksw
-
-    case "-d":
-    set do_doc = 1
-    shift
-    breaksw
-
-    default:
-	echo "Usage: get_sizes [-t] [-d]" > /dev/tty
-	exit 1
-    breaksw
-  endsw
-end
-
-if ("$do_doc") then
-	set cmd = "grep html $LOCALDIR/var/sizes.$DOC"
-	set size_line = `$cmd`
-	if ($status != 0) then
-		echo "$0 : <$cmd> - failed" > /dev/tty
-		exit 1
-	endif
-	set htmldoc_size = $size_line[2]
-
-	set cmd = "grep ps $LOCALDIR/var/sizes.$DOC"
-	set size_line = `$cmd`
-	if ($status != 0) then
-		echo "$0 : <$cmd> - failed" > /dev/tty
-		exit 1
-	endif
-	set psdoc_size = $size_line[2]
-
-	if ("$do_total") then
-		@ total = $psdoc_size + $htmldoc_size
-		echo "$total"
-	else
-		echo " $htmldoc_size $psdoc_size"
-	endif
-else
-	set cmd = "grep bin $LOCALDIR/var/sizes.$SYSTEM"
-	set size_line = `$cmd`
-	if ($status != 0) then
-		echo "$0 : <$cmd> - failed" > /dev/tty
-		exit 1
-	endif
-	set bin_size = $size_line[2]
-
-	set cmd = "grep include $LOCALDIR/var/sizes.$SYSTEM"
-	set size_line = `$cmd`
-	if ($status != 0) then
-		echo "$0 : <$cmd> - failed" > /dev/tty
-		exit 1
-	endif
-	set inc_size = $size_line[2]
-
-	set cmd = "grep lib $LOCALDIR/var/sizes.$SYSTEM"
-	set size_line = `$cmd`
-	if ($status != 0) then
-		echo "$0 : <$cmd> - failed" > /dev/tty
-		exit 1
-	endif
-	set lib_size = $size_line[2]
-
-	set cmd = "grep man $LOCALDIR/var/sizes.$SYSTEM"
-	set size_line = `$cmd`
-	if ($status != 0) then
-		echo "$0 : <$cmd> - failed" > /dev/tty
-		exit 1
-	endif
-	set man_size = $size_line[2]
-
-	if ("$do_total") then
-		@ total = $bin_size + $inc_size + $lib_size + $man_size
-		echo "$total"
-	else
-		echo "$bin_size $inc_size $lib_size $man_size"
-	endif
+if ($#argv == 1) then
+    if ("$argv[1]" != "-t") then
+        echo "Usage: get_sizes [-t]" > /dev/tty
+        exit 1
+    endif
+    set do_total = 1
 endif
+
+    set cmd = "grep bin $LOCALDIR/var/sizes.$SYSTEM"
+    set size_line = `$cmd`
+    if ($status != 0) then
+        echo "$0 : <$cmd> - failed" > /dev/tty
+        exit 1
+    endif
+    set bin_size = $size_line[2]
+
+    set cmd = "grep include $LOCALDIR/var/sizes.$SYSTEM"
+    set size_line = `$cmd`
+    if ($status != 0) then
+        echo "$0 : <$cmd> - failed" > /dev/tty
+        exit 1
+    endif
+    set inc_size = $size_line[2]
+
+    set cmd = "grep lib $LOCALDIR/var/sizes.$SYSTEM"
+    set size_line = `$cmd`
+    if ($status != 0) then
+        echo "$0 : <$cmd> - failed" > /dev/tty
+        exit 1
+    endif
+    set lib_size = $size_line[2]
+
+    set cmd = "grep man $LOCALDIR/var/sizes.$SYSTEM"
+    set size_line = `$cmd`
+    if ($status != 0) then
+        echo "$0 : <$cmd> - failed" > /dev/tty
+        exit 1
+    endif
+    set man_size = $size_line[2]
+
+    if ("$do_total") then
+        @ total = $bin_size + $inc_size + $lib_size + $man_size
+        echo "$total"
+    else
+        echo "$bin_size $inc_size $lib_size $man_size"
+    endif
 
 exit 0
 
diff --git a/install/install/select_config b/install/install/select_config
--- a/install/install/select_config
+++ b/install/install/select_config
@@ -1,6 +1,6 @@
 #!/bin/csh -f
 #
-#      $Id: select_config,v 1.7 1995-08-22 21:17:37 haley Exp $
+#      $Id: select_config,v 1.8 1995-10-05 21:59:03 haley Exp $
 #
 #########################################################################
 #                                                                       #
@@ -10,65 +10,43 @@
 #                                                                       #
 #########################################################################
 #
-#	File:		select_config
+#   File:       select_config
 #
-#	Author:		John Clyne
-#			National Center for Atmospheric Research
-#			PO 3000, Boulder, Colorado
+#   Author:     John Clyne
+#           National Center for Atmospheric Research
+#           PO 3000, Boulder, Colorado
 #
-#	Date:		Tue Sep 29 09:05:18 MDT 1992
+#   Date:       Tue Sep 29 09:05:18 MDT 1992
 #
-#	Description:	Select an installation configuration. On success,
-#			exit status == 0, select_config writes the installation
-#			type (Basic-Installation or Custom-Installation), 
-#			the bin, include, lib, and man paths (or the documentation
-#			paths) in that order, to the standard output. If no
-#			selection was made select_config will not write anything
-#			to stdout.  If an error occurs exit status will be 1.
+#   Description:    Select an installation configuration. On success,
+#           exit status == 0, select_config writes the installation
+#           type (Basic-Installation or Custom-Installation), 
+#           the bin, include, lib, and man paths, in that order,
+#           to the standard output. If no selection was made
+#           select_config will not write anything to stdout.
+#           If an error occurs exit status will be 1.
 #
-#	Usage:		select_config [-d]
+#   Usage:      select_config
 #
-#	Environment:	SYSTEM		: system type
-#			LOCALDIR	: path to install system
+#   Environment:    SYSTEM      : system type
+#           LOCALDIR    : path to install system
 #
-#	Files:
+#   Files:
 #
-#
-#   Options:    -doc        : look up documentation paths
 #
 
 onintr cleanup
 
-set do_doc = 0
-
-if ($#argv > 1) then
-	echo "Usage: select_config [-doc]" > /dev/tty
-	exit 1
-endif
-
-if ($#argv == 1) then
-  if ("$argv[1]" == "-doc") then
-    set do_doc = 1
-  else
-	echo "Usage: select_config [-doc]" > /dev/tty
-	exit 1
-  endif
-endif
-
 clear > /dev/tty
 
-if ("$do_doc") then
-  set total_size = `$LOCALDIR/get_sizes -t -d`
-else
-  set total_size = `$LOCALDIR/get_sizes -t`
-endif
+set total_size = `$LOCALDIR/get_sizes -t`
 if ($status != 0) then
-	exit 1
+    exit 1
 endif
 
 set done = 0
 while (! $done) 
-	clear > /dev/tty
+    clear > /dev/tty
 cat <<EOF > /dev/tty
 
 
@@ -81,138 +59,100 @@ cat <<EOF > /dev/tty
 
 
 Please select the type of installation that you wish to perform. 
-	
-	1.  Basic Installation			[ $total_size KB required ]
-	    The Basic Installation is recommended.
+    
+    1.  Basic Installation          [ $total_size KB required ]
+        The Basic Installation is recommended.
 
-        2.  Custom Installation			[ required disk space varies ]
-	    Optional software components and installation directories
+    2.  Custom Installation         [ required disk space varies ]
+        Optional software components and installation directories
 
-        3.  Help on Installation Choices
+    3.  Help on Installation Choices
 
-
-
-	0.  Return to previous menu
+    0.  Return to previous menu
 
 EOF
 
-	echo -n "    Select: " > /dev/tty
-	set answer =  $<
-	switch ("$answer")
-		case "1":
-			clear > /dev/tty
-			#
-			# We already know the installation directories. We
-			# call get_paths to determine if there is enough 
-			# disk space
-			#
-            if ("$do_doc") then
-			  set paths = `$LOCALDIR/get_paths -default -doc`
+    echo -n "    Select: " > /dev/tty
+    set answer =  $<
+    switch ("$answer")
+        case "1":
+            clear > /dev/tty
+            #
+            # We already know the installation directories. We
+            # call get_paths to determine if there is enough 
+            # disk space
+            #
+            set paths = `$LOCALDIR/get_paths -default`
+            if ($status == 0) then
+                set done = 1
+                set type = "Basic-Installation"
             else
-			  set paths = `$LOCALDIR/get_paths -default`
+                $LOCALDIR/pause
             endif
-			if ($status == 0) then
-				set done = 1
-				set type = "Basic-Installation"
-			else
-				$LOCALDIR/pause
-			endif
-			breaksw
+            breaksw
 
-		case "2":
-			clear > /dev/tty
-			#
-			# get the installation directory paths
-			#
-            if ("$do_doc") then
-  			  set paths = `$LOCALDIR/get_paths -doc`
+        case "2":
+            clear > /dev/tty
+            #
+            # get the installation directory paths
+            #
+            set paths = `$LOCALDIR/get_paths`
+            if ($status == 0) then
+                set done = 1
+                set type = "Custom-Installation"
             else
-  			  set paths = `$LOCALDIR/get_paths`
+                $LOCALDIR/pause
             endif
-			if ($status == 0) then
-				set done = 1
-				set type = "Custom-Installation"
-			else
-				$LOCALDIR/pause
-			endif
-			breaksw
+            breaksw
 
-		case "3":
-		  	source $LOCALDIR/config/paths.$SYSTEM
-			clear > /dev/tty
-            if ("$do_doc") then
-  			  cat <<EOF > /dev/tty
+        case "3":
+            source $LOCALDIR/config/paths.$SYSTEM
+            clear > /dev/tty
+            cat <<EOF > /dev/tty
 
-	The Basic Documentation Installation installs all documentation
-	components of NCAR Graphics Version $VERSION:
 
-		HTML documents are installed to $htmldoc_path.
-		PostScript documents are installed to $psdoc_path. 
+    The Basic Installation installs all components of NCAR Graphics
+    Version $VERSION:
 
-	The Custom Installation allows you some freedom in choosing which 
-	components of the NCAR Graphics documentation are installed. For
-	example, if you only need to install the HTML documentation, you
-	should select the Custom Installation. In addition, the custom
-	installation allows you to choose the installation paths of the
-	PostScript and HTML documentation directories.
+        Executables are installed to $bin_path. 
+        Include files are installed to $inc_path.
+        Libraries are installed to $lib_path. 
+        Man pages are installed to $man_path.
+
+    The Custom Installation allows you some freedom in choosing which 
+    components of NCAR Graphics are installed. For example, if you only
+    need to install the man pages you should select the Custom 
+    Installation. In addition, the custom installation allows you
+    to choose the installation paths of the bin, lib, man, and 
+    include directories.
+
+    It is highly recommended that less experienced installers choose
+    the basic installation.
 EOF
-            else
-  			  cat <<EOF > /dev/tty
+            $LOCALDIR/pause
 
-	The Basic Installation installs all components of NCAR Graphics
-	Version $VERSION:
+            breaksw
 
-		Executables are installed to $bin_path. 
-		Include files are installed to $inc_path.
-		Libraries are installed to $lib_path. 
-		Man pages are installed to $man_path.
+        case "0":
+            exit 0
+            breaksw
 
-	The Custom Installation allows you some freedom in choosing which 
-	components of NCAR Graphics are installed. For example, if you only
-	need to install the man pages you should select the Custom 
-	Installation. In addition, the custom installation allows you
-	to choose the installation paths of the bin, lib, man, and 
-	include directories.
+        case ""
+            breaksw
 
-	It is highly recommended that less experienced installers choose
-	the basic installation.
-EOF
-            endif
-       
-			$LOCALDIR/pause
-
-			breaksw
-
-		case "0":
-			exit 0
-			breaksw
-
-		case ""
-			breaksw
-
-		default
-			echo "Invalid option <$answer>" > /dev/tty
-			$LOCALDIR/pause
-	endsw
+        default
+            echo "Invalid option <$answer>" > /dev/tty
+            $LOCALDIR/pause
+    endsw
 end
 
 
-if ("$do_doc") then
-  set htmldoc_path = $paths[1]
-  set psdoc_path = $paths[2]
+set bin_path = $paths[1]
+set inc_path = $paths[2]
+set lib_path = $paths[3]
+set man_path = $paths[4]
 
-  echo $type $htmldoc_path $psdoc_path
-
-else
-  set bin_path = $paths[1]
-  set inc_path = $paths[2]
-  set lib_path = $paths[3]
-  set man_path = $paths[4]
-
-  echo $type $bin_path $inc_path $lib_path $man_path
-
-endif
-
+echo $type $bin_path $inc_path $lib_path $man_path
 
 exit 0
 
diff --git a/install/install/select_src b/install/install/select_src
--- a/install/install/select_src
+++ b/install/install/select_src
@@ -1,42 +1,42 @@
 #!/bin/csh -f
 #
-#      $Id: select_src,v 1.5 1995-08-22 21:17:37 haley Exp $
+#      $Id: select_src,v 1.6 1995-10-05 21:59:03 haley Exp $
 #
 #########################################################################
-#									#
-#			   Copyright (C)  1992				#
-#	     University Corporation for Atmospheric Research		#
-#			   All Rights Reserved				#
-#									#
+#                                   #
+#              Copyright (C)  1992              #
+#        University Corporation for Atmospheric Research        #
+#              All Rights Reserved              #
+#                                   #
 #########################################################################
 #
-#	File:		select_src
+#   File:       select_src
 #
-#	Author:		John Clyne
-#			National Center for Atmospheric Research
-#			PO 3000, Boulder, Colorado
+#   Author:     John Clyne
+#           National Center for Atmospheric Research
+#           PO 3000, Boulder, Colorado
 #
-#	Date:		Wed Nov 11 16:15:38 MST 1992
+#   Date:       Wed Nov 11 16:15:38 MST 1992
 #
-#	Description:	Prompt the user for an input source for the 
-#			distribution. Upon success (exit 0) select_src
-#			write the installation souce type to standard output.
-#			The source type may be one of (cdrom, tar-file, tape).
+#   Description:    Prompt the user for an input source for the 
+#           distribution. Upon success (exit 0) select_src
+#           write the installation souce type to standard output.
+#           The source type may be one of (cdrom, tar-file, tape).
 #
-#	Usage:		select_src
+#   Usage:      select_src
 #
-#	Environment:
+#   Environment:
 #
-#	Files:
+#   Files:
 #
 #
-#	Options:
+#   Options:
 
 onintr cleanup
 
 set done = 0
 while (! $done) 
-	clear > /dev/tty
+    clear > /dev/tty
 cat <<EOF > /dev/tty
 
 
@@ -50,64 +50,64 @@ cat <<EOF > /dev/tty
 
 
 Please select the type of installation that you wish to perform. 
-	
-	1.  Install from cdrom
-	2.  Install from tape
-	3.  Install from tar file
-	4.  Help
+    
+    1.  Install from cdrom
+    2.  Install from tape
+    3.  Install from tar file
+    4.  Help
 
-	0.  Return to previous menu
+    0.  Return to previous menu
 
 EOF
 
-	echo -n "    Select: " > /dev/tty
-	set answer =  $<
+    echo -n "    Select: " > /dev/tty
+    set answer =  $<
 
-	switch ("$answer")
+    switch ("$answer")
 
-	case "1":
-		set source = cdrom
-		set done = 1
-		breaksw
+    case "1":
+        set source = cdrom
+        set done = 1
+        breaksw
 
-	case "2":
-		set source = tape
-		set done = 1
-		breaksw
+    case "2":
+        set source = tape
+        set done = 1
+        breaksw
 
-	case "3":
-		set source = tar-file
-		set done = 1
-		breaksw
+    case "3":
+        set source = tar-file
+        set done = 1
+        breaksw
 
-	case "4":
-		clear > /dev/tty
-		cat <<EOF > /dev/tty
+    case "4":
+        clear > /dev/tty
+        cat <<EOF > /dev/tty
 
 
-	If your NCAR Graphics distribution is contained on a CD-ROM select 
-	"1" (Install from cdrom).
+    If your NCAR Graphics distribution is contained on a CD-ROM select 
+    "1" (Install from cdrom).
 
-	If your NCAR Graphics distribution is contained on a tape select 
-	"2" (Install from tape).
+    If your NCAR Graphics distribution is contained on a tape select 
+    "2" (Install from tape).
 
-	If your NCAR Graphics distribution is contained in a UNIX tar file
-	select "3" (Install from tar file).
+    If your NCAR Graphics distribution is contained in a UNIX tar file
+    select "3" (Install from tar file).
 EOF
-		$LOCALDIR/pause
-		breaksw
+        $LOCALDIR/pause
+        breaksw
 
-	case "0":
-		exit 1
-		breaksw
+    case "0":
+        exit 1
+        breaksw
 
-	case ""
-		breaksw
+    case ""
+        breaksw
 
-	default
-		echo "Invalid option <$answer>" > /dev/tty
-		$LOCALDIR/pause
-	endsw
+    default
+        echo "Invalid option <$answer>" > /dev/tty
+        $LOCALDIR/pause
+    endsw
 end
 
 echo $source
