Updated to:
 - remove the question on the old PNG driver
 - correct some old links
 - reference "HDF-EOS2" and "HDF-EOS5" correctly
 - correct some spelling errors


git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@11177 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -1,6 +1,6 @@
 #!/bin/csh -f
 #
-#      $Id: Configure,v 1.52 2009-12-21 19:16:42 haley Exp $
+#      $Id: Configure,v 1.53 2010-01-18 21:43:31 haley Exp $
 #
 #########################################################################
 #																		#
@@ -15,7 +15,7 @@
 #				National Center for Atmospheric Research
 #				POB 3000, Boulder, Colorado
 #
-#	$Date: 2009-12-21 19:16:42 $
+#	$Date: 2010-01-18 21:43:31 $
 #
 #	Description:	I took pieces of the old configure script to
 #					build this one.
@@ -145,8 +145,8 @@ set buildxlibstuff=`$makecmd XSTUFF`
 echo -n "..."
 set buildtriangle=`$makecmd TRIANGLESTUFF`
 echo -n "..."
-set buildpng=`$makecmd PNGSTUFF`
-echo -n "..."
+# set buildpng=`$makecmd PNGSTUFF`
+# echo -n "..."
 set buildcairo=`$makecmd CAIROSTUFF`
 echo -n "..."
 set buildgdal=`$makecmd GDALSTUFF`
@@ -188,7 +188,7 @@ if ($?verbose_option) then
 ======================================================================
 
 	This question and answer session will allow you to configure
-	NCAR Graphics for installation.  It creates a file
+	NCL and NCAR Graphics for installation.  It creates a file
 	"Site.local" in the "config" directory that defines Site
 	specific information.  This procedure will also check that the
 	directories specified are accessible and that the required
@@ -239,13 +239,15 @@ if (-e ni) then
 	The NCAR Command Language (NCL) is a free interpreted language
         designed specifically for scientific data processing and
         visualization. NCL has robust file input and output. It can
-        read in netCDF, HDF4, HDF4-EOS, GRIB, binary and ASCII data.
-        It requires several external packages (like netCDF and HDF),
-        and has several optional packages you can build in (UDUNITS,
-        Triangle, HDF-EOS, and Vis5D functions).
+        read in netCDF, HDF4, HDF-EOS2, HDF-EOS5,  GRIB 1/2, binary
+        and ASCII data.
+
+        It requires several external packages (like netCDF and HDF4),
+        and has several optional packages you can build in (UDUNITS2,
+        Triangle, HDF-EOS2, HDF-EOS5, and Vis5D functions).
 
         NCL is a separate software package from NCAR Graphics. You
-        don't don't need it in order to use NCAR Graphics.
+        don't don't need it in order to build or use NCAR Graphics.
 
 ======================================================================
 "EOF"
@@ -344,7 +346,7 @@ if ($?verbose_option) then
 	file space.  On most systems, the directory "/tmp" is the
 	logical choice.  You may specify a different directory to
 	use for this purpose.  The directory must be writable by
-	NCAR Grahpics users.  This procedure will check only to
+	NCL/NCAR Graphics users.  This procedure will check only to
 	make sure that the directory specified is writable by the
 	installation process.
 
@@ -402,35 +404,38 @@ if ($?verbose_option) then
 endif
 
 #
+# Don't ask about PNG support here, because PNG support is now
+# part of cairo.
+#
 # PNG
 #
-if ($?verbose_option) then
-  cat <<"EOF"
-======================================================================
-
-	There's some experimental code in the GKS library in NCAR
-	Graphics that allows you to create PNG files in the
-	same way that you can output to an NCGM, PS, or PDF file. 
-	If you want to try this code, then you'll need to download
-	and install the png and zlib source code and link against
-	their libraries whenever you link an NCAR Graphics program.
-
-======================================================================
-"EOF"
-endif
-
-echo ""
-echo "Build png/zlib support (optional) into GKS library? ($buildpng)"
-echo "(Requires the external png/zlib libraries available from"
-echo "http://www.libpng.org/pub/png/libpng.html and http://www.zlib.net/) "
-echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
-set answer="$<"
-if ("$answer" == "q") goto cleanup
-if (("$answer" != "") && ("$answer" != "$buildpng")) then
-	set buildpng = $answer
-	set newbuildpng
-    set altered
-endif
+# if ($?verbose_option) then
+#   cat <<"EOF"
+# ======================================================================
+# 
+# 	There's some experimental code in the GKS library in NCAR
+# 	Graphics that allows you to create PNG files in the
+# 	same way that you can output to an NCGM, PS, or PDF file. 
+# 	If you want to try this code, then you'll need to download
+# 	and install the png and zlib source code and link against
+# 	their libraries whenever you link an NCAR Graphics program.
+# 
+# ======================================================================
+# "EOF"
+# endif
+# 
+# echo ""
+# echo "Build png/zlib support (optional) into GKS library? ($buildpng)"
+# echo "(Requires the external png/zlib libraries available from"
+# echo "http://www.libpng.org/pub/png/libpng.html and http://www.zlib.net/) "
+# echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
+# set answer="$<"
+# if ("$answer" == "q") goto cleanup
+# if (("$answer" != "") && ("$answer" != "$buildpng")) then
+# 	set buildpng = $answer
+# 	set newbuildpng
+#     set altered
+# endif
 
 #
 # Cairo.
@@ -439,10 +444,11 @@ if ($?verbose_option) then
   cat <<"EOF"
 ======================================================================
 
-	If you want access to the cairo workstations, like PNG,
-	then you'll need to download several packages along with
-        cairo. This is experimental for now, so unless you know
-        what you're doing, answer "n" to this question.
+	If you want access to the cairo workstations, which will
+        give you PNG and smaller PDF files, then you'll need to
+        download several packages along with cairo. This is
+        experimental for now, so unless you know what you're doing,
+        answer "n" to this question.
 
 ======================================================================
 "EOF"
@@ -489,15 +495,16 @@ endif
 if ("$buildncl" == "y" || "$buildncl" == "Y") then
   echo ""
   echo "Informational note: since you are building NCL, you must build the"
-  echo "external HDF libraries available from http://hdf.ncsa.uiuc.edu/."
+  echo "external HDF-4 libraries available from "
+  echo "http://www.hdfgroup.org/release4/obtain.html."
   echo "Please see the instructions at"
   echo "http://www.ncl.ucar.edu/Download/build_from_src.shtml#HDF-4"
   echo "to make sure your HDF software is built according to NCL requirements."
 else
   echo ""
-  echo "Build HDF support (optional) into raster library? ($buildhdf)"
-  echo "(Requires the external HDF libraries available from http://hdf.ncsa.uiuc.edu/) "
-  echo "(Note: HDF is required if you plan to build NCL.)"
+  echo "Build HDF-4 support (optional) into raster library? ($buildhdf)"
+  echo "(Requires the external HDF-4 libraries available from http://www.hdfgroup.org/release4/obtain.html) "
+  echo "(Note: HDF-4 is required if you plan to build NCL HDF-5 is not.)"
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -522,7 +529,7 @@ if (("$buildhdf" == "y") || ("$buildhdf" == "Y")) then
 endif
 
 #
-# Only ask about NetCDF- UDUNITS, HDFEOS, HDFEOS5, Triangle, Vis5d+, and
+# Only ask about NetCDF- UDUNITS, HDF-EOS2, HDF-EOS5, Triangle, Vis5d+, and
 # other external software support if we are actually planning to
 # build NCL.
 #
@@ -575,7 +582,9 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
         you with compression support, and the ability to write netCDF-4
         classic files. Not all aspects of netCDF-4 files are fully
         supported yet, like multiple-unlimited dimensions and
-        new types. THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
+        new types.
+
+        THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
         If you built your NetCDF-4 library with the "--enable-netcdf-4"
         option, then you should answer "y" to this question.
@@ -607,6 +616,7 @@ if ($?verbose_option) then
 
 	If you want to be able to read shapefiles, then you'll need to
         download GDAL and supporting packages (PROJ4).
+
 	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
 ======================================================================
@@ -633,10 +643,11 @@ endif
     cat <<"EOF"
 ======================================================================
 
-	The udunits library supports many different time formats, and
+	The udunits-2 library supports many different time formats, and
 	some of its functionality is available as built-in functions
 	in NCL. In order to have this functionality, you must have the
-	V1.x (not V2.x) libudunits.a library installed on your system.
+	V2.x (not V1.x) libudunits2.a library installed on your system.
+
 	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
 ======================================================================
@@ -644,9 +655,9 @@ endif
   endif
 
   echo ""
-  echo "Build Udunits support (optional) into NCL ($buildudunits)"
-  echo "(Requires the external V1.x Udunits [not V2.x] library available from"
-  echo "http://www.unidata.ucar.edu/packages/udunits/) "
+  echo "Build Udunits-2 support (optional) into NCL ($buildudunits)"
+  echo "(Requires the external V2.x Udunits [not V1.x] library available from"
+  echo "http://www.unidata.ucar.edu/software/udunits/udunits-2/udunits2.html) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -668,8 +679,9 @@ endif
 	Enabling this option will allow for writing Vis5d+ files.  It
 	DOES NOT enable NCL or NCAR GRAPHICS to visualize such files.
 	In order to have this functionality, you must have the
-	NCAR-supplied libraries installed on your system.  THIS
-	LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
+	NCAR-supplied libraries installed on your system.
+
+	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
 ======================================================================
 "EOF"
@@ -689,25 +701,26 @@ endif
   endif
 
 #
-# HDFEOS
+# HDF-EOS2
 #
   if ($?verbose_option) then
     cat <<"EOF"
 ======================================================================
 
-	The hdfeos library supports the HDF-EOS data format, and NCL
+	The hdfeos library supports the HDF-EOS2 data format, and NCL
 	has some capability to read these files in. In order to have
-	this functionality, you must have the HDFEOS libraries
-	installed on your system.  THIS LIBRARY IS NOT NEEDED FOR
-	BUILDING NCAR GRAPHICS.
+	this functionality, you must have the HDF-EOS2 libraries
+	installed on your system.
+
+        THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
 ======================================================================
 "EOF"
   endif
 
   echo ""
-  echo "Build HDFEOS support (optional) into NCL ($buildhdfeos)"
-  echo "(Requires the external HDFEOS libraries available from"
+  echo "Build HDF-EOS2 support (optional) into NCL ($buildhdfeos)"
+  echo "(Requires the external HDF-EOS2 libraries available from"
   echo "http://newsroom.gsfc.nasa.gov/sdptoolkit/toolkit.html) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
@@ -719,7 +732,7 @@ endif
   endif
 
 #
-# HDFEOS5
+# HDF-EOS5
 #
   if ($?verbose_option) then
     cat <<"EOF"
@@ -727,17 +740,18 @@ endif
 
 	The hdfeos5 library supports the HDF-EOS5 data format, and NCL
 	has some capability to read these files in. In order to have
-	this functionality, you must have the HDFEOS5 library
-	installed on your system. THIS LIBRARY IS NOT NEEDED FOR
-	BUILDING NCAR GRAPHICS.
+	this functionality, you must have the HDF-EOS5 library
+	installed on your system. 
+
+        THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
 ======================================================================
 "EOF"
   endif
 
   echo ""
-  echo "Build HDFEOS5 support (optional) into NCL ($buildhdfeos)"
-  echo "(Requires the external HDFEOS5 library available from"
+  echo "Build HDF-EOS5 support (optional) into NCL ($buildhdfeos)"
+  echo "(Requires the external HDF-EOS5 library available from"
   echo "ftp://edhs1.gsfc.nasa.gov/pub) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
@@ -806,8 +820,7 @@ endif
 
   echo ""
   echo "Build OPeNDAP support (optional) into NCL ($builddods)"
-  echo "(Requires the external netCDF software available from"
-  echo "http://www.unidata.ucar.edu/packages/dods/home/sw.html) "
+  echo "(Requires the external netCDF software available from Unidata) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -1137,14 +1150,17 @@ if ($?newbuildhdf) then
 	endif
 endif
 
-if ($?newbuildpng) then
-	if ("$buildpng" == "y") then
-		echo "#define BuildPNG 1" >> Site.local
-	else
-		echo "#define BuildPNG 0" >> Site.local
-		echo "#define PNGlib" >> Site.local
-	endif
-endif
+#
+# This is the old PNG stuff. Commented out for now.
+#
+# if ($?newbuildpng) then
+# 	if ("$buildpng" == "y") then
+# 		echo "#define BuildPNG 1" >> Site.local
+# 	else
+# 		echo "#define BuildPNG 0" >> Site.local
+# 		echo "#define PNGlib" >> Site.local
+# 	endif
+# endif
 
 /* This is turned off for now. */
 if ($?newbuildcairo  && "$buildcairo" == "y") then
