Cleaned up Configure a bit: corrected links, removed "cairo" question, added more verbose output.
git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@10841 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -1,6 +1,6 @@
 #!/bin/csh -f
 #
-#      $Id: Configure,v 1.48 2009-05-08 21:21:10 haley Exp $
+#      $Id: Configure,v 1.49 2009-05-11 16:41:35 haley Exp $
 #
 #########################################################################
 #																		#
@@ -15,7 +15,7 @@
 #				National Center for Atmospheric Research
 #				POB 3000, Boulder, Colorado
 #
-#	$Date: 2009-05-08 21:21:10 $
+#	$Date: 2009-05-11 16:41:35 $
 #
 #	Description:	I took pieces of the old configure script to
 #					build this one.
@@ -52,7 +52,7 @@ if ($#argv > 0) then
 			set ncar_option
 			breaksw
 		default:
-			echo "Error: Unknown command-line arguement."
+			echo "Error: Unknown command-line argument."
 			exit 1
 			breaksw
 		endsw
@@ -182,14 +182,16 @@ echo ""
 
 if ($?verbose_option) then
   cat <<"EOF"
+======================================================================
 
 	This question and answer session will allow you to configure
-	NCAR Graphics for installation.  It creates a file "Site.local"
-	in the "config" directory that defines Site specific information.
-	This procedure will also check that the
+	NCAR Graphics for installation.  It creates a file
+	"Site.local" in the "config" directory that defines Site
+	specific information.  This procedure will also check that the
 	directories specified are accessible and that the required
 	system support is available.
 
+======================================================================
 "EOF"
 
   echo -n "Enter Return to continue, or q(quit) > "
@@ -197,6 +199,7 @@ if ($?verbose_option) then
   if ("$answer" == "q") goto cleanup
 
   cat <<"EOF"
+======================================================================
 
 	Informational text (like the paragraph you are reading) is
 	indented by one tab stop.  Questions are left justified;
@@ -205,17 +208,22 @@ if ($?verbose_option) then
 	entering a Return (carriage return) or you may enter any of
 	the other valid responses.
 
+======================================================================
 "EOF"
 
-  echo -n "Enter Return to continue, or q(quit) > "
-  set answer="$<"
-  if ("$answer" == "q") goto cleanup
+endif
 
+if (! $?verbose_option) then
+  echo "======================================================================"
+  echo "Run 'Configure -v' if you want more information about the"
+  echo "questions that follow."
+  echo "======================================================================"
 endif
 
 echo -n "Enter Return to continue, or q(quit) > "
 set answer="$<"
 if ("$answer" == "q") goto cleanup
+
 
 #
 # Whether to build NCL or not.
@@ -223,6 +231,7 @@ if ("$answer" == "q") goto cleanup
 if (-e ni) then
   if ($?verbose_option) then
     cat <<"EOF"
+======================================================================
 
 	The NCAR Command Language (NCL) is a free interpreted language
         designed specifically for scientific data processing and
@@ -234,6 +243,8 @@ if (-e ni) then
 
         NCL is a separate software package from NCAR Graphics. You
         don't don't need it in order to use NCAR Graphics.
+
+======================================================================
 "EOF"
   endif
 
@@ -264,12 +275,14 @@ endif
 proc_parent:
 if ($?verbose_option) then
   cat <<"EOF"
+======================================================================
 
 	The NCL/NCAR Graphics software must be installed in a parent 
         directory containing subdirectiries 'bin', 'include', 'lib',
         and 'man'. This procedure will make sure that these
         directories are writable by the installation process.
 
+======================================================================
 "EOF"
 endif
 
@@ -322,6 +335,7 @@ proc_tmp:
 
 if ($?verbose_option) then
   cat <<"EOF"
+======================================================================
 
 	A couple of the translators make use of temporary
 	file space.  On most systems, the directory "/tmp" is the
@@ -331,6 +345,7 @@ if ($?verbose_option) then
 	make sure that the directory specified is writable by the
 	installation process.
 
+======================================================================
 "EOF"
 endif
 
@@ -362,6 +377,7 @@ endif
 
 if ($?verbose_option) then
   cat <<"EOF"
+======================================================================
 
 	The next few questions concern some of the applications in
 	NCAR Graphics that allow the user to manipulate and view
@@ -378,6 +394,7 @@ if ($?verbose_option) then
 	basic X11 libraries.  If you don't have these libraries,
 	answer "n" to the next question.
 
+======================================================================
 "EOF"
 endif
 
@@ -386,6 +403,7 @@ endif
 #
 if ($?verbose_option) then
   cat <<"EOF"
+======================================================================
 
 	There's some experimental code in the GKS library in NCAR
 	Graphics that allows you to create PNG files in the
@@ -394,12 +412,13 @@ if ($?verbose_option) then
 	and install the png and zlib source code and link against
 	their libraries whenever you link an NCAR Graphics program.
 
+======================================================================
 "EOF"
 endif
 
 echo ""
 echo "Build png/zlib support (optional) into GKS library? ($buildpng)"
-echo "(requires the external png/zlib libraries available from"
+echo "(Requires the external png/zlib libraries available from"
 echo "http://www.libpng.org/pub/png/libpng.html and http://www.zlib.net/) "
 echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
 set answer="$<"
@@ -411,22 +430,25 @@ if (("$answer" != "") && ("$answer" != "$buildpng")) then
 endif
 
 #
-# Cairo
+# Cairo. This is turned off for now.
 #
+if (0) then
 if ($?verbose_option) then
   cat <<"EOF"
+======================================================================
 
 	If you want access to the cairo workstations, like PNG,
 	then you'll need to download several packages along with
         cairo. This is experimental for now, so unless you know
         what you're doing, answer "n" to this question.
 
+======================================================================
 "EOF"
 endif
 
 echo ""
 echo "Build cairo support (optional) into GKS library? (we recommend 'n') ($buildcairo)"
-echo "(requires the cairo and other external libraries available from"
+echo "(Requires the cairo and other external libraries available from"
 echo "http://cairographics.org/) "
 echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
 set answer="$<"
@@ -436,12 +458,14 @@ if (("$answer" != "") && ("$answer" != "$buildcairo")) then
 	set newbuildcairo
     set altered
 endif
+endif
 
 #
 # HDF. This is not optional if you are building NCL.
 #
 if ($?verbose_option) then
   cat <<"EOF"
+======================================================================
 
 	If you answered yes to the "build NCL?" question, then you must
 	build the HDF libraries according to the NCL/NCAR Graphics
@@ -457,6 +481,7 @@ if ($?verbose_option) then
 	NCAR Graphics, then you only need to build HDF if you need
 	HDF support built into the NCAR Graphics raster library.
 
+======================================================================
 "EOF"
 endif
 
@@ -470,7 +495,7 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
 else
   echo ""
   echo "Build HDF support (optional) into raster library? ($buildhdf)"
-  echo "(requires the external HDF libraries available from http://hdf.ncsa.uiuc.edu/) "
+  echo "(Requires the external HDF libraries available from http://hdf.ncsa.uiuc.edu/) "
   echo "(Note: HDF is required if you plan to build NCL.)"
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
@@ -506,6 +531,7 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
 #
   if ($?verbose_option) then
     cat <<"EOF"
+======================================================================
 
 	The Triangle code is what allows you to generate triangular
         meshes so that you can contour non-uniform grids.
@@ -517,13 +543,14 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
         ni/src/lib/hlu subdirectory, answer "y" to this question,
         and you should be set.
 
+======================================================================
 "EOF"
   endif
 
   echo ""
   echo "Build Triangle support (optional) into NCL ($buildtriangle)"
   echo "Requires 'triangle.c' and 'triangle.h' code from"
-  echo " http://www.cs.cmu.edu/~quake/triangle.html."
+  echo "http://www.cs.cmu.edu/~quake/triangle.html"
   echo "You must agree to the license restrictions in the above URL,"
   echo "download these two files, and put them in ni/src/lib/hlu"
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
@@ -541,19 +568,26 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
 #
   if ($?verbose_option) then
     cat <<"EOF"
+======================================================================
 
-	Linking with the netCDF-4 library currently provides you
-        with compression support, and the ability to write netCDF-4
+	Linking with the netCDF-4 enabled library currently provides
+        you with compression support, and the ability to write netCDF-4
         classic files. Not all aspects of netCDF-4 files are fully
         supported yet, like multiple-unlimited dimensions and
         new types. THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
+        If you built your NetCDF-4 library with the "--enable-netcdf-4"
+        option, then you should answer "y" to this question.
+
+======================================================================
 "EOF"
   endif
 
   echo ""
-  echo "Build NetCDF-4 support (optional) into NCL ($buildnetcdf4)"
-  echo "(requires the external NetCDF-4 library available from http://www.unidata.ucar.edu/software/netcdf-4/) "
+  echo "If you are using NetCDF V4.x, did you enable NetCDF-4 support ($buildnetcdf4)?"
+  echo "(Requires compiling NetCDF-4 library available from"
+  echo "http://www.unidata.ucar.edu/software/netcdf/"
+  echo "and building with '---enable-netcdf-4') "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -568,18 +602,19 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
 #
 if ($?verbose_option) then
   cat <<"EOF"
+======================================================================
 
 	If you want to be able to read shapefiles, then you'll need to
-        download GDAL and supporting packages (PROJ4). This is
-        experimental for now, so unless you know what you're doing,
-        answer "n" to this question.
+        download GDAL and supporting packages (PROJ4).
+	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
+======================================================================
 "EOF"
 endif
 
 echo ""
-echo "Build GDAL support (optional) into NCL? (we recommend 'n') ($buildgdal)"
-echo "(requires GDAL and PROJ4 from http://www.gdal.org/ and "
+echo "Build GDAL support (optional) into NCL? ($buildgdal)"
+echo "(Requires GDAL and PROJ4 from http://www.gdal.org/ and "
 echo "http://trac.osgeo.org/proj/) "
 echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
 set answer="$<"
@@ -595,19 +630,22 @@ endif
 #
   if ($?verbose_option) then
     cat <<"EOF"
+======================================================================
 
-	The udunits library supports many different time formats,
-	and some of its functionality is available as built-in
-	functions in NCL. In order to have this functionality, you must
-        have the libudunits.a library installed on your system.  THIS
-        LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
+	The udunits library supports many different time formats, and
+	some of its functionality is available as built-in functions
+	in NCL. In order to have this functionality, you must have the
+	V1.x (not V2.x) libudunits.a library installed on your system.
+	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
+======================================================================
 "EOF"
   endif
 
   echo ""
   echo "Build Udunits support (optional) into NCL ($buildudunits)"
-  echo "(requires the external Udunits library available from http://www.unidata.ucar.edu/packages/udunits/) "
+  echo "(Requires the external V1.x Udunits [not V2.x] library available from"
+  echo "http://www.unidata.ucar.edu/packages/udunits/) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -622,20 +660,24 @@ endif
 #
   if ($?verbose_option) then
     cat <<"EOF"
+======================================================================
 
-	The Vis5d+ library supports OpenGL-based volumetric visualization
-	for scientific datasets in 3+ dimensions.  Enabling this option will
-	allow for writing Vis5d+ files.  It DOES NOT enable NCL or NCAR GRAPHICS
-	to visualize such files.  In order to have this functionality, you must
-	have the NCAR-supplied libraries installed on your system.
-	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
+	The Vis5d+ library supports OpenGL-based volumetric
+	visualization for scientific datasets in 3+ dimensions.
+	Enabling this option will allow for writing Vis5d+ files.  It
+	DOES NOT enable NCL or NCAR GRAPHICS to visualize such files.
+	In order to have this functionality, you must have the
+	NCAR-supplied libraries installed on your system.  THIS
+	LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
+======================================================================
 "EOF"
   endif
 
   echo ""
   echo "Build Vis5d+ support (optional) into NCL ($buildv5d)"
-  echo "(requires the external Vis5d+ software available from http://vis5d.sourceforge.net/)"
+  echo "(Requires the external Vis5d+ software available from"
+  echo "http://vis5d.sourceforge.net/) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -650,19 +692,23 @@ endif
 #
   if ($?verbose_option) then
     cat <<"EOF"
+======================================================================
 
 	The hdfeos library supports the HDF-EOS data format, and NCL
 	has some capability to read these files in. In order to have
 	this functionality, you must have the HDFEOS libraries
-	installed on your system.  THIS LIBRARY IS NOT NEEDED FOR
+	installed on your system.  A password may have to be obtained
+        to download this software. THIS LIBRARY IS NOT NEEDED FOR
 	BUILDING NCAR GRAPHICS.
 
+======================================================================
 "EOF"
   endif
 
   echo ""
   echo "Build HDFEOS support (optional) into NCL ($buildhdfeos)"
-  echo "(requires the external HDFEOS libraries available from http://hdfeos.gsfc.nasa.gov/hdfeos/index.cfm) "
+  echo "(Requires the external HDFEOS libraries available from"
+  echo "http://newsroom.gsfc.nasa.gov/sdptoolkit/toolkit.html) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -677,21 +723,22 @@ endif
 #
   if ($?verbose_option) then
     cat <<"EOF"
+======================================================================
 
-    GRIB2 support is currently limited to TIGGE-specific data
-    files.  Support for GRIB2 data from other data centers is
-    planned.  In order to have this functionality, you must have
-    both the NCEP GRIB2 decoder library and the jasper JPEG2000
-    library installed on your system.  THIS LIBRARY IS NOT NEEDED
-    FOR BUILDING NCAR GRAPHICS.
+    In order to have support for reading GRIB2 files with NCL, you
+    must have both the NCEP GRIB2 decoder library and the jasper
+    JPEG2000 library installed on your system.  THESE LIBRARIES ARE
+    NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
+======================================================================
 "EOF"
   endif
 
   echo ""
   echo "Build GRIB2 support (optional) into NCL ($buildgrib2)"
-  echo "(requires the GRIB2 decoder library:  http://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/"
-  echo " and jasper:  http://www.ece.uvic.ca/~mdadams/jasper/)"
+  echo "(Requires the GRIB2 decoder (g2clib) library and jasper from"
+  echo "http://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/ and"
+  echo "http://www.ece.uvic.ca/~mdadams/jasper/) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -706,23 +753,31 @@ endif
 #
   if ($?verbose_option) then
     cat <<"EOF"
+======================================================================
 
-	OPeNDAP is a protocol for requesting and transporting data across the web.
-	The current OPeNDAP Data Access Protocol (DAP) simplifies all aspects of
-	scientific data networking, allowing simple access to remote data. Local
-	data can be made accessible to remote locations regardless of local
-	storage format.  In order to have this functionality, you must have
-	the Unidata-supplied OPeNDAP-enabled netCDF libraries installed on your
-	system, which are available from this site:
-            http://www.opendap.org
-	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
+	OPeNDAP is a protocol for requesting and transporting data
+	across the web.  The current OPeNDAP Data Access Protocol
+	(DAP) simplifies all aspects of scientific data networking,
+	allowing simple access to remote data. Local data can be made
+	accessible to remote locations regardless of local storage
+	format.  In order to have this functionality, you must have
+	the Unidata-supplied OPeNDAP-enabled netCDF libraries
+	installed on your system, which are available from this site:
+	http://www.opendap.org
 
+        This can be a difficult package to build, so only select this
+        option if you really need this support.
+
+        THIS LIBRARY IS NOT NEEDED FOR BUILDING	NCAR GRAPHICS.
+
+======================================================================
 "EOF"
   endif
 
   echo ""
   echo "Build OPeNDAP support (optional) into NCL ($builddods)"
-  echo "(requires the external netCDF software available from http://www.unidata.ucar.edu/packages/dods/home/sw.html)"
+  echo "(Requires the external netCDF software available from"
+  echo "http://www.unidata.ucar.edu/packages/dods/home/sw.html) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -771,7 +826,7 @@ endif
 # 
 #   echo ""
 #   echo "Build PyNGL ($buildpyngl)"
-#   echo "(requires Python from python.org and Numeric from www.pfdubois.com/numpy/"
+#   echo "(Requires Python from python.org and Numeric from www.pfdubois.com/numpy/"
 #   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
 #   set answer="$<"
 #   if ("$answer" == "q") goto cleanup
@@ -1059,8 +1114,11 @@ if ($?newbuildpng) then
 	endif
 endif
 
+/* This is turned off for now. */
+if (0) then
 if ($?newbuildcairo  && "$buildcairo" == "y") then
 	echo "#define BuildCAIRO 1" >> Site.local
+endif
 endif
 
 if ($?newbuildnetcdf4) then
