I modified the "Configure" script so it now creates the toplevel Makefile, so we no longer need the Makefile.ini.  To use the ncar local configuration (Site) file instead of building a "Site.local" file use the -ncar option to Configure.
jeff


git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@2080 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -1,6 +1,6 @@
 #!/bin/csh -f
 #
-#      $Id: Configure,v 1.6 1994-04-08 20:32:40 boote Exp $
+#      $Id: Configure,v 1.7 1994-05-05 21:40:45 boote Exp $
 #
 #########################################################################
 #									#
@@ -38,11 +38,13 @@ if (($cmddir != $cmdname) && ($cmddir != ".")) then
 	goto cleanup
 endif
 
-if (! -d config) then
-	echo "Where is the config subdir???"
-	echo "It should be at ./config"
+if ((! -d config) || (! -x config/ymkmf)) then
+	echo "Where is the config/ymkmf program???"
+	echo "It should be at ./config/ymkmf"
 	goto cleanup
 endif
+
+set ymkmfcmd=./config/ymkmf
 
 if ($#argv > 0) then
 	while ($#argv)
@@ -52,6 +54,9 @@ if ($#argv > 0) then
 			breaksw
 		case "-v":
 			set verbose_option
+			breaksw
+		case "-ncar":
+			set ncar_option
 			breaksw
 		default:
 			echo "Error: Unknown command-line arguement."
@@ -85,14 +90,22 @@ end
 
 if(! $?makedependcmd) set nomakedepend
 
-if (-e config/Site.local) then
+if (-e ./config/Site.local) then
 	echo "	*** WARNING:There is a previous configuration saved."
 	echo ""
 	echo "Overwrite existing configuration? (n)"
 	echo -n "Enter Return(default), y(yes), n(no), or q(quit) > "
 	set answer=$<
-	if ("$answer" != "y") goto cleanup
+	if ("$answer" == "q") goto cleanup
+	if ("$answer" == "n") goto shortcut
+	if ($?ncar_option) then
+		rm ./config/Site.local
+	endif
 endif
+
+if ($?ncar_option) goto shortcut
+
+onintr extra_cleanup
 
 echo "/* Default Config */" > config/Site.local
 echo "#define EmptySite" >> config/Site.local
@@ -101,7 +114,7 @@ if ($?nomakedepend) echo "#define NoMakeDepend" >> config/Site.local
 echo ""
 echo "Building top-level Makefile to determine System defaults"
 echo ""
-$makecmd -f Makefile.ini me
+$ymkmfcmd
 if ($status) then
 	echo "Unable to build Makefile - fix above errors and re-run."
 	goto cleanup
@@ -132,7 +145,8 @@ echo -n "..."
 set ncargversion=`$makecmd VERS`
 echo ""
 /bin/rm Makefile
-ln -s Makefile.ini Makefile
+
+onintr cleanup
 
 QuestionAndAnswer:
 echo ""
@@ -757,6 +771,21 @@ echo "#endif /* SecondSite */" >> Site.local
 
 cd ..
 
+shortcut:
+if ($?ncar_option) then
+	set conf_type = "ncar local"
+else
+	set conf_type = "current"
+endif
+echo ""
+echo "Building Top-level Makefile with $conf_type configuration options"
+echo ""
+$ymkmfcmd
+if ($status) then
+	echo "Unable to build Makefile - fix above errors and re-run."
+	goto cleanup
+endif
+
 #
 # Installation step
 #
@@ -790,6 +819,10 @@ if ($?verbose_option) then
 endif
 
 exit 0
+
+extra_cleanup:
+rm -f Makefile
+rm -f config/Site.local
 
 cleanup:
 echo ""
