NCL-609/NCL-781: Making HDF4 optional
git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/branches/NCL_6_0_0@11834 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -153,6 +153,8 @@ set buildgdal=`$makecmd GDALSTUFF`
 echo -n "..."
 set buildhdf=`$makecmd HDFSTUFF`
 echo -n "..."
+set buildrasterhdf=`$makecmd RASTERHDFSTUFF`
+echo -n "..."
 set buildnetcdf4=`$makecmd NETCDF4STUFF`
 echo -n "..."
 set buildudunits=`$makecmd UDUNITSSTUFF`
@@ -247,8 +249,8 @@ if (-e ni) then
 	read in netCDF, HDF4, HDF-EOS2, HDF-EOS5, HDF5, GRIB 1/2, binary
 	and ASCII data.
 
-	It requires several external packages (like netCDF and HDF4),
-	and has several optional packages you can build in (UDUNITS2,
+	It requires some external packages (like netCDF),
+	and has several optional packages you can build in (HDF4, UDUNITS2,
 	Triangle, HDF-EOS2, HDF-EOS5, HDF5, and Vis5D functions).
 
 	NCL is a separate software package from NCAR Graphics. You
@@ -473,15 +475,18 @@ if (("$answer" != "") && ("$answer" != "$buildcairo")) then
 endif
 
 #
-# HDF. This is not optional if you are building NCL.
+# HDF4 is now optional for NCL. Nevertheless because it is also an option 
+# for the raster library, ask about it here prior to the NCL-only section. 
 #
 if ($?verbose_option) then
   cat <<"EOF"
 ======================================================================
 
-	If you answered yes to the "build NCL?" question, then you must
-	build the HDF libraries according to the NCL/NCAR Graphics
-	source code installation instructions at:
+	NCL can optionally provide read/write access to HDF4 and and 
+        read access to HDF-EOS2 files. If you answered yes to the 
+        "build NCL?" question, and you want HDF4 and/or HDF-EOS2 file
+        support then you must build the HDF libraries according to 
+        the NCL/NCAR Graphics source code installation instructions at:
 
 	http://www.ncl.ucar.edu/Download/build_from_src.shtml#HDF-4
 
@@ -499,31 +504,50 @@ endif
 
 if ("$buildncl" == "y" || "$buildncl" == "Y") then
   echo ""
-  echo "Informational note: since you are building NCL, you must build the"
-  echo "external HDF-4 libraries available from "
-  echo "http://www.hdfgroup.org/release4/obtain.html."
+  echo "Build HDF4 support (optional) into NCL? ($buildhdf)"
+  echo "Informational note: HDF4 is no longer required to build NCL,"
+  echo "but it is a prerequisite if you need HDF-EOS2 support."
+  echo "(Requires external HDF-4 libraries available from "
+  echo "http://www.hdfgroup.org/release4/obtain.html)"
   echo "Please see the instructions at"
   echo "http://www.ncl.ucar.edu/Download/build_from_src.shtml#HDF-4"
   echo "to make sure your HDF software is built according to NCL requirements."
-else
-  echo ""
-  echo "Build HDF-4 support (optional) into raster library? ($buildhdf)"
-  echo "(Requires the external HDF-4 libraries available from http://www.hdfgroup.org/release4/obtain.html) "
-  echo "(Note: HDF-4 is required if you plan to build NCL HDF-5 is not.)"
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
   if (("$answer" != "") && ("$answer" != "$buildhdf")) then
-  	set buildhdf = $answer
-  	set newbuildhdf
+      set buildhdf = $answer
+      set newbuildhdf
+      set altered
+  endif
+  echo ""
+  echo "Also build HDF4 support (optional) into raster library? ($buildrasterhdf)"
+  echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
+  set answer="$<"
+  if ("$answer" == "q") goto cleanup
+  if (("$answer" != "") && ("$answer" != "$buildrasterhdf")) then
+      set buildrasterhdf = $answer
+      set newbuildrasterhdf
+      set altered
+  endif
+else
+  echo ""
+  echo "Build HDF4 support (optional) into raster library? ($buildrasterhdf)"
+  echo "(Requires the external HDF4 libraries available from http://www.hdfgroup.org/release4/obtain.html) "
+  echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
+  set answer="$<"
+  if ("$answer" == "q") goto cleanup
+  if (("$answer" != "") && ("$answer" != "$buildhdf")) then
+    set buildrasterhdf = $answer
+    set newbuildrasterhdf
     set altered
   endif
 endif
-
 set hdfwithszip = "n"
-if (("$buildhdf" == "y") || ("$buildhdf" == "Y")) then
+if (("$buildhdf" == "y") || ("$buildhdf" == "Y") || \
+    ("$buildrasterhdf" == "y") || ("$buildrasterhdf" == "Y")) then
     echo ""
-    echo "Did you build HDF-4 with szip support? ($hdfwithszip)"
+    echo "Did you build HDF4 with szip support? ($hdfwithszip)"
     echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
     set answer="$<"
     if ("$answer" == "q") goto cleanup
@@ -687,7 +711,7 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
 
 	If you want to use the experimental interface to gridspec, you 
 	will need to link to the CF library. This library is now built 
-        as part of NetCDF V4.1 and later --with-libcf is set.  
+        as part of NetCDF V4.1 and later if '--with-libcf' is set.  
 
 	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
@@ -783,7 +807,8 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
 	The hdfeos library supports the HDF-EOS2 data format, and NCL
 	has some capability to read these files in. In order to have
 	this functionality, you must have the HDF-EOS2 libraries
-	installed on your system.
+	installed on your system. You must also have answered yes to
+        including support for HDF4 in NCL.
 
 	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
 
@@ -794,7 +819,8 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
   echo ""
   echo "Build HDF-EOS2 support (optional) into NCL ($buildhdfeos)"
   echo "(Requires the external HDF-EOS2 libraries available from"
-  echo "http://newsroom.gsfc.nasa.gov/sdptoolkit/toolkit.html) "
+  echo "http://newsroom.gsfc.nasa.gov/sdptoolkit/toolkit.html. You"
+  echo "must also have included support for HDF4.) "
   echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
   set answer="$<"
   if ("$answer" == "q") goto cleanup
@@ -804,36 +830,6 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
         set altered
   endif
 
-#
-# HDF-EOS5
-#
-  if ($?verbose_option) then
-    cat <<"EOF"
-======================================================================
-
-	The hdfeos5 library supports the HDF-EOS5 data format, and NCL
-	has some capability to read these files in. In order to have
-	this functionality, you must have the HDF-EOS5 library
-	installed on your system. 
-
-	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
-
-======================================================================
-"EOF"
-  endif
-
-  echo ""
-  echo "Build HDF-EOS5 support (optional) into NCL ($buildhdfeos5)"
-  echo "(Requires the external HDF-EOS5 library available from"
-  echo "ftp://edhs1.gsfc.nasa.gov/pub) "
-  echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
-  set answer="$<"
-  if ("$answer" == "q") goto cleanup
-  if (("$answer" != "") && ("$answer" != "$buildhdfeos5")) then
-  	set buildhdfeos5 = $answer
-  	set newbuildhdfeos5
-        set altered
-  endif
 
 #
 # HDF5
@@ -863,6 +859,37 @@ if ("$buildncl" == "y" || "$buildncl" == "Y") then
   if (("$answer" != "") && ("$answer" != "$buildhdf5")) then
   	set buildhdf5 = $answer
   	set newbuildhdf5
+        set altered
+  endif
+
+#
+# HDF-EOS5
+#
+  if ($?verbose_option) then
+    cat <<"EOF"
+======================================================================
+
+	The hdfeos5 library supports the HDF-EOS5 data format, and NCL
+	has some capability to read these files in. In order to have
+	this functionality, you must have the HDF-EOS5 library
+	installed on your system. 
+
+	THIS LIBRARY IS NOT NEEDED FOR BUILDING NCAR GRAPHICS.
+
+======================================================================
+"EOF"
+  endif
+
+  echo ""
+  echo "Build HDF-EOS5 support (optional) into NCL ($buildhdfeos5)"
+  echo "(Requires the external HDF-EOS5 library available from"
+  echo "ftp://edhs1.gsfc.nasa.gov/pub)"
+  echo -n "Enter Return (default), y(yes), n(no), or q(quit) > "
+  set answer="$<"
+  if ("$answer" == "q") goto cleanup
+  if (("$answer" != "") && ("$answer" != "$buildhdfeos5")) then
+  	set buildhdfeos5 = $answer
+  	set newbuildhdfeos5
         set altered
   endif
 
@@ -906,6 +933,7 @@ else
   set buildgrib2 = "n"
   set buildv5d = "n"
   set builddods = "n"
+  set buildgridspec = "n"
   set netcdfwithdap = "n"
   set netcdflib = ""
   set newbuildhdfeos
@@ -917,6 +945,7 @@ else
   set newbuildgrib2
   set newbuildv5d
   set newbuilddods
+  set newbuildgridspec
   set altered
 endif
 
@@ -1221,14 +1250,28 @@ endif
 
 echo "" >> Site.local
 
-if ($?newbuildhdf) then
-	if ("$buildhdf" == "y") then
+if ($?newbuildrasterhdf) then
+	if ("$buildrasterhdf" == "y") then
 		echo "#define BuildRasterHDF 1" >> Site.local
 	else
 		echo "#define BuildRasterHDF 0" >> Site.local
-		echo "#define HDFlib" >> Site.local
+		if ($buildhdf != "y") then
+		    echo "#define HDFlib" >> Site.local
+	        endif
 	endif
 endif
+
+if ($?newbuildhdf) then
+	if ("$buildhdf" == "y") then
+		echo "#define BuildHDF4 1" >> Site.local
+	else
+		echo "#define BuildHDF4 0" >> Site.local
+		if ($buildrasterhdf != "y") then
+		    echo "#define HDFlib" >> Site.local
+	        endif
+	endif
+endif
+
 
 #
 # This is the old PNG stuff. Commented out for now.
