Modified yMakefile to create a "manl" directory under the man directory (if needed).  In the future, this will be changed depending on whether the man pages are to be split up into man1, man3, man5, etc.
git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@589 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/yMakefile b/yMakefile
--- a/yMakefile
+++ b/yMakefile
@@ -106,9 +106,9 @@ dirs::
 	@-if (test ! -d $(MANROOT) || test ! -w $(MANROOT)) then \
 	echo "Installation Error - $(MANROOT) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(MANPATH)) then mkdir $(MANPATH); else continue; fi
-	@-if (test ! -d $(MANPATH) || test ! -w $(MANPATH)) then \
-	echo "Installation Error - $(MANPATH) is not writeable"; exit 1; \
+	@-if (test ! -d $(MANLPATH)) then mkdir $(MANLPATH); else continue; fi
+	@-if (test ! -d $(MANLPATH) || test ! -w $(MANLPATH)) then \
+	echo "Installation Error - $(MANLPATH) is not writeable"; exit 1; \
 	else continue; fi
 	@-if (test ! -d $(FONTCAPPATH)) then mkdir $(FONTCAPPATH); \
 	else continue; fi
