Added TUTORIALPATH to "dirs" target.
git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@507 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/yMakefile b/yMakefile
--- a/yMakefile
+++ b/yMakefile
@@ -131,6 +131,11 @@ dirs::
 	@-if (test ! -d $(TESTSPATH) || test ! -w $(TESTSPATH)) then \
 	echo "Installation Error - $(TESTSPATH) is not writeable"; exit 1; \
 	else continue; fi
+	@-if (test ! -d $(TUTORIALPATH)) then mkdir $(TUTORIALPATH); \
+	else continue; fi
+	@-if (test ! -d $(TUTORIALPATH) || test ! -w $(TUTORIALPATH)) then \
+	echo "Installation Error - $(TUTORIALPATH) is not writeable"; exit 1; \
+	else continue; fi
 	@-if (test ! -d $(XAPPPATH)) then mkdir $(XAPPPATH); else continue; fi
 	@-if (test ! -d $(XAPPPATH) || test ! -w $(XAPPPATH)) then \
 	echo "Installation Error - $(XAPPPATH) is not writeable"; exit 1; \
