Added ROBJDIR to list of SUBDIRS and to list of directories that get made under the "make dirs" target.
git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@785 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/yMakefile b/yMakefile
--- a/yMakefile
+++ b/yMakefile
@@ -3,8 +3,8 @@ NCARG	= .
 SUBDIRS	= common ncarg2d ncarview
 
 NEWDIRS	= $(BINPATH) $(LIBPATH) $(INCPATH) $(MANPATH) $(FONTCAPPATH) \
-	$(GRAPHCAPPATH) $(DBPATH) $(EXAMPLESPATH) $(TESTSPATH) $(XAPPPATH)\
-	$(TUTORIALPATH)
+	$(GRAPHCAPPATH) $(DBPATH) $(ROBJPATH) $(EXAMPLESPATH) $(TESTSPATH) \
+	$(XAPPPATH) $(TUTORIALPATH)
 
 all::	dirs
 
@@ -33,6 +33,7 @@ Info:
 	echo "	Include Directory            " $(INCPATH); \
 	echo "	Manpage Directory            " $(MANPATH); \
 	echo "	Data Base Directory          " $(DBPATH); \
+	echo "	Relocatable Obj. Directory   " $(ROBJPATH); \
 	echo "	Examples Directory           " $(EXAMPLESPATH); \
 	echo "	Tutorial Directory           " $(TUTORIALPATH); \
 	echo "	Test Directory               " $(TESTSPATH); \
@@ -123,6 +124,11 @@ dirs::
 	@-if (test ! -d $(DBPATH)) then mkdir $(DBPATH); else continue; fi
 	@-if (test ! -d $(DBPATH) || test ! -w $(DBPATH)) then \
 	echo "Installation Error - $(DBPATH) is not writeable"; exit 1; \
+	else continue; fi
+	@-if (test ! -d $(ROBJPATH)) then mkdir $(ROBJPATH); \
+	else continue; fi
+	@-if (test ! -d $(ROBJPATH) || test ! -w $(ROBJPATH)) then \
+	echo "Installation Error - $(ROBJPATH) is not writeable"; exit 1; \
 	else continue; fi
 	@-if (test ! -d $(EXAMPLESPATH)) then mkdir $(EXAMPLESPATH); \
 	else continue; fi
