Rewrote the Configure script using "perl".
Created a new top-level yMakefile to incorporate the new macros
introduced in the config files.


git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@465 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/yMakefile b/yMakefile
--- a/yMakefile
+++ b/yMakefile
@@ -1,12 +1,9 @@
-#
-#	$Id: yMakefile,v 1.1.1.1 1992-04-17 22:29:30 ncargd Exp $
-#
 NCARG	= .
 
-SUBDIRS	= common ncarg2d ncarview
+SUBDIRS	= common ncarview
 
-NEWDIRS	= $(BINDIR) $(LIBDIR) $(MANDIR) $(FONTCAPDIR) $(GRAPHCAPDIR) \
-	$(DBDIR) $(EXAMPLEDIR) $(TESTDIR)
+NEWDIRS	= $(BINPATH) $(LIBPATH) $(INCPATH) $(MANPATH) $(FONTCAPPATH) \
+	$(GRAPHCAPPATH) $(DBPATH) $(EXAMPLEPATH) $(TESTPATH) $(XAPPPATH)
 
 all::	dirs
 
@@ -30,17 +27,19 @@ Info:
 #ifdef BuildUnsupportedAthenaApplications
 	@echo "	NCAR View will include unsupported X applications
 #endif
-	@echo "	Binary Directory        " $(BINDIR); \
-	echo "	Library Directory       " $(LIBDIR); \
-	echo "	Data Base Directory     " $(DBDIR); \
-	echo "	Manpage Directory       " $(MANDIR); \
-	echo "	Examples Directory      " $(EXAMPLEDIR); \
-	echo "	Test Directory          " $(TESTDIR); \
-	echo "	f77 Flags               " $(FFLAGS); \
-	echo "	cc Flags                " $(CFLAGS);
+	@echo "	Binary Directory             " $(BINPATH); \
+	echo "	Library Directory            " $(LIBPATH); \
+	echo "	Include Directory            " $(INCPATH); \
+	echo "	Manpage Directory            " $(MANPATH); \
+	echo "	Data Base Directory          " $(DBPATH); \
+	echo "	Examples Directory           " $(EXAMPLEPATH); \
+	echo "	Test Directory               " $(TESTPATH); \
+	echo "	X App. Defaults Directory    " $(XAPPPATH); \
+	echo "	f77 Flags                    " $(FFLAGS); \
+	echo "	cc Flags                     " $(CFLAGS);
 
 Config:
-	@cd $(CONFIGDIR); $(MAKE) clean all
+	@cd $(CONFIGPATH); $(MAKE) clean all
 
 # The "All" target rebuilds the Makefile hierarchy, rebuilds
 # all libraries, rebuilds all out-of-date executables, and
@@ -71,64 +70,71 @@ Everything: Config
 	@$(MAKE) clean all install
 	@echo "Finished making <Everything>."
 
-# The Binaries target does the same thing as the Everything target plus it 
-# builds new binaries for the current system. Only execute "make Binaries"
-# when you need to rebuild the binaries located in the binary distribution
-# directory (currently ncarview/bin/$ARCH
-
-Binaries: Config
-	@echo ""
-	@echo "Making <Binaries>."
-	@$(YMAKE)
-	@$(MAKE) Info
-	@$(MAKE) Makefiles
-	@$(MAKE) cleanbin all install
-	@echo "Finished making <Binaries>."
-
-
 dirs::
-	@-if (test ! -d $(BINDIR)) then mkdir $(BINDIR); else continue; fi
-	@-if (test ! -d $(BINDIR) || test ! -w $(BINDIR)) then \
-	echo "Installation Error - $(BINDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(BINROOT)) then mkdir $(BINROOT); else continue; fi
+	@-if (test ! -d $(BINROOT) || test ! -w $(BINROOT)) then \
+	echo "Installation Error - $(BINROOT) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(LIBDIR)) then mkdir $(LIBDIR); else continue; fi
-	@-if (test ! -d $(LIBDIR) || test ! -w $(LIBDIR)) then \
-	echo "Installation Error - $(LIBDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(BINPATH)) then mkdir $(BINPATH); else continue; fi
+	@-if (test ! -d $(BINPATH) || test ! -w $(BINPATH)) then \
+	echo "Installation Error - $(BINPATH) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(MANDIR)) then mkdir $(MANDIR); else continue; fi
-	@-if (test ! -d $(MANDIR) || test ! -w $(MANDIR)) then \
-	echo "Installation Error - $(MANDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(LIBROOT)) then mkdir $(LIBROOT); else continue; fi
+	@-if (test ! -d $(LIBROOT) || test ! -w $(LIBROOT)) then \
+	echo "Installation Error - $(LIBROOT) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(FONTCAPDIR)) then mkdir $(FONTCAPDIR); \
+	@-if (test ! -d $(LIBPATH)) then mkdir $(LIBPATH); else continue; fi
+	@-if (test ! -d $(LIBPATH) || test ! -w $(LIBPATH)) then \
+	echo "Installation Error - $(BINPATH) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(FONTCAPDIR) || test ! -w $(FONTCAPDIR)) then \
-	echo "Installation Error - $(FONTCAPDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(LIBNCARGPATH)) then mkdir $(LIBNCARGPATH); \
 	else continue; fi
-	@-if (test ! -d $(GRAPHCAPDIR)) then mkdir $(GRAPHCAPDIR); \
+	@-if (test ! -d $(LIBNCARGPATH) || test ! -w $(LIBNCARGPATH)) then \
+	echo "Installation Error - $(LIBPATH) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(GRAPHCAPDIR) || test ! -w $(GRAPHCAPDIR)) then \
-	echo "Installation Error - $(GRAPHCAPDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(INCROOT)) then mkdir $(INCROOT); else continue; fi
+	@-if (test ! -d $(INCROOT) || test ! -w $(INCROOT)) then \
+	echo "Installation Error - $(INCPATH) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(DBDIR)) then mkdir $(DBDIR); else continue; fi
-	@-if (test ! -d $(DBDIR) || test ! -w $(DBDIR)) then \
-	echo "Installation Error - $(DBDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(INCPATH)) then mkdir $(INCPATH); else continue; fi
+	@-if (test ! -d $(INCPATH) || test ! -w $(INCPATH)) then \
+	echo "Installation Error - $(INCPATH) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(EXAMPLEDIR)) then mkdir $(EXAMPLEDIR); \
+	@-if (test ! -d $(MANROOT)) then mkdir $(MANROOT); else continue; fi
+	@-if (test ! -d $(MANROOT) || test ! -w $(MANROOT)) then \
+	echo "Installation Error - $(MANROOT) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(EXAMPLEDIR) || test ! -w $(EXAMPLEDIR)) then \
-	echo "Installation Error - $(EXAMPLEDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(MANPATH)) then mkdir $(MANPATH); else continue; fi
+	@-if (test ! -d $(MANPATH) || test ! -w $(MANPATH)) then \
+	echo "Installation Error - $(MANPATH) is not writeable"; exit 1; \
 	else continue; fi
-	@-if (test ! -d $(TESTDIR)) then mkdir $(TESTDIR); else continue; fi
-	@-if (test ! -d $(TESTDIR) || test ! -w $(TESTDIR)) then \
-	echo "Installation Error - $(TESTDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(FONTCAPPATH)) then mkdir $(FONTCAPPATH); \
 	else continue; fi
-#ifdef	BuildUnsupportedAthenaApplications
-dirs::
-	@-if (test ! -d $(XAPPDIR)) then mkdir $(XAPPDIR); else continue; fi
-	@-if (test ! -d $(XAPPDIR) || test ! -w $(XAPPDIR)) then \
-	echo "Installation Error - $(XAPPDIR) is not writeable"; exit 1; \
+	@-if (test ! -d $(FONTCAPPATH) || test ! -w $(FONTCAPPATH)) then \
+	echo "Installation Error - $(FONTCAPPATH) is not writeable"; exit 1; \
 	else continue; fi
-#endif
+	@-if (test ! -d $(GRAPHCAPPATH)) then mkdir $(GRAPHCAPPATH); \
+	else continue; fi
+	@-if (test ! -d $(GRAPHCAPPATH) || test ! -w $(GRAPHCAPPATH)) then \
+	echo "Installation Error - $(GRAPHCAPPATH) is not writeable"; exit 1; \
+	else continue; fi
+	@-if (test ! -d $(DBPATH)) then mkdir $(DBPATH); else continue; fi
+	@-if (test ! -d $(DBPATH) || test ! -w $(DBPATH)) then \
+	echo "Installation Error - $(DBPATH) is not writeable"; exit 1; \
+	else continue; fi
+	@-if (test ! -d $(EXAMPLESPATH)) then mkdir $(EXAMPLESPATH); \
+	else continue; fi
+	@-if (test ! -d $(EXAMPLESPATH) || test ! -w $(EXAMPLESPATH)) then \
+	echo "Installation Error - $(EXAMPLESPATH) is not writeable"; exit 1; \
+	else continue; fi
+	@-if (test ! -d $(TESTSPATH)) then mkdir $(TESTSPATH); else continue; fi
+	@-if (test ! -d $(TESTSPATH) || test ! -w $(TESTSPATH)) then \
+	echo "Installation Error - $(TESTSPATH) is not writeable"; exit 1; \
+	else continue; fi
+	@-if (test ! -d $(XAPPPATH)) then mkdir $(XAPPPATH); else continue; fi
+	@-if (test ! -d $(XAPPPATH) || test ! -w $(XAPPPATH)) then \
+	echo "Installation Error - $(XAPPPATH) is not writeable"; exit 1; \
+	else continue; fi
 
 MakefilesSubdirs($(SUBDIRS))
 InstallSubdirs($(SUBDIRS))
@@ -136,12 +142,12 @@ CleanSubdirs($(SUBDIRS))
 
 #ifdef BuildCFTBinaries
 install::
-	@$(NCARG)/utils/makecftbin $(LIBDIR)
+	@$(NCARG)/utils/makecftbin $(LIBPATH)
 #endif
 
 #ifdef BuildNCARGSourceLibrary
 install::
-	@chmod 600 $(LIBDIR)/src*.a
-	@chmod u+s $(BINDIR)/ncargsrcx
-	touch $(LIBDIR)/ncargsrc.stats
+	@chmod 600 $(LIBPATH)/src*.a
+	@chmod u+s $(BINPATH)/ncargsrcx
+	touch $(LIBPATH)/ncargsrc.stats
 #endif
