Updated script so that it will automatically look for g95 and then gfortran if g77 is not found on Mac or Linux systems.
git-svn-id: https://subversion.ucar.edu/ncldev/ncarg/trunk@9517 10fe2890-8a40-4696-8b1d-7ccbb19c398e

diff --git a/ni/src/scripts/WRAPIT b/ni/src/scripts/WRAPIT
--- a/ni/src/scripts/WRAPIT
+++ b/ni/src/scripts/WRAPIT
@@ -279,14 +279,34 @@ while ($#argv)
 end      
 
 # check for g77 compiler if needed
-if (($OS == Linux && $f90c == g77) || ($OS == Darwin && $f90c == g77) || \
-     $OS == FreeBSD) then 
+if (($OS == Linux && $f90c == g77) || $OS == FreeBSD) then 
   which g77
   if ($status) then
     echo "FATAL ERROR: GNU g77 compiler NOT found."
     echo EXITING WRAPIT
     echo " "
     exit 1
+  endif
+endif
+
+# check for g77, gfortran, g95 compiler if needed
+if (($OS == Linux && $f90c == g77) || ($OS == Darwin && $f90c == g77) || $OS == FreeBSD) then 
+  which g77 >! /dev/null
+  if ($status) then
+    which g95 >! /dev/null
+    if ($status) then
+      which gfortran >! /dev/null
+      if ($status) then
+        echo "FATAL ERROR: g77, g95, gfortran compilers NOT found."
+        echo EXITING WRAPIT
+        echo " "
+        exit 1
+      else
+        set f90c = gfortran
+      endif
+    else
+      set f90c = g95
+    endif
   endif
 endif
 
